prow/config/config.yaml
This job must be manually triggered for now.  Once I verify it works,
"always_run" should be changed to "true" to run on all PRs.
=> Add a shellcheck job for metal3-dev-env.

prow/Makefile
This change makes "make validate" run checkconfig the same way that CI
does.  This image version matches the version of prow currently
deployed.
=> Makefile: Use prow checkconfig container for "make validate".

prow/README.md
Split the README between notes on the cluster that runs prow and prow
itself.  For the cluster, add a section that points to cert-manager,
which the cluster is running to manage its SSL certificates.
=> Add notes on how SSL certificates are managed.

label_sync/.gitignore, label_sync/Makefile, label_sync/README.md, label_sync/config_example.sh, label_sync/labels.yaml, label_sync/sync_labels.sh
This makes use of kubernetes test-infra to setup the labels on our
repos.  Copy config_example.sh and edit the values with the
configuration you desire, and then run `make` to see a *dry run* of what
it would do.
To apply the changes, run `make confirm`
=> Add label_sync tool from kuberenetes to sync labels

prow/config/config.yaml
I've turned on spyglass, which is the job artifacts viewer.  This
config is needed to start generating URLs that point to this artifact
viewer.
Related to issue #15
=> plank: Add job_url_prefix_config.

prow/config/config.yaml
This should let us see the build log, start/end time, and the log of
cloning the source for the job.
Part of issue #15
=> spyglass: Configure some artifact viewers.

prow/config/config.yaml
I misinterpreted the config here.  The build log and and clone log
should use the "buildlog" lense, which shows a log file.
More docs here:
https://github.com/kubernetes/test-infra/tree/master/prow/spyglass
Part of issue #15
=> spyglass: Fix lenses for viewing log files.

prow/config/config.yaml
This adds jobs to run shellcheck, markdownlint, go vet, go fmt, and go
test.
This also replaces everything we were doing on this repo with
travis-ci.
Part of issue #18
=> Add CI jobs for cluster-api-provider-baremetal.

prow/config/config.yaml
This job is now working, so turn it on by default.
=> Always run the unit job for capbm.

prow/config/config.yaml
This works now, so we can run it by default.
=> Enable govet job by default in capbm

prow/config/config.yaml
This adds govet, markdownlint, shellcheck, gofmt, and unit jobs for
baremetal-operator.  They will currently not run by default, and will
only run if specifically requested.
This depends on https://github.com/metal3-io/baremetal-operator/pull/321
=> Add jobs for baremetal-operator

prow/config/config.yaml
v1alpha2 unit tests require a different kubebuilder version and different utilities, hence using a different image. This comit separates the unit test job for v1alpha2 branches from master branch
=> Separate unit test job for CAPBM v1alpha2

prow/config/config.yaml
The required scripts have all merged as of PR
https://github.com/metal3-io/baremetal-operator/pull/321 so these jobs
can now run by default.
=> prow: Run barmetal-operator jobs by default.

prow/config/config.yaml
the v1alpha2 branch of CAPBM was moved to master and the old master to 
v1alpha1, this commit adapts the CI jobs.
=> Modify CAPBM jobs for v1alpha2 master

prow/config/config.yaml
That prevents having a PR blocking the merge pool because the
requirements are not fulfilled for merging in Github
=> Tide : Get required jobs from branch protection

OWNERS
It's best if I'm not the only approver, and stbenjam and maelk are the
next two that have probably looked at the CI infra the most.
=> Add stbenjam and maelk to OWNERS

prow/config/config.yaml
The previous version (1.12) ignores go modules by default.
=> Upgrade golang containers to 1.13.7

jenkins/scripts/files/run_integration_tests.sh
Otherwise use the default runtime in metal3-dev-env, podman
Podman is the only one supported in CentOS8 for now so we should
stop to enforce docker as it is not supported in CentOS8
=> Jenkins: use docker for e2e testing in Ubuntu only

jenkins/scripts/files/run_integration_tests.sh, jenkins/scripts/integration_test.sh
It was based before on the target OS, instead of metal3-dev-env OS
=> Jenkins: base runtime on metal3-dev-env OS distribution

label_sync/labels.yaml
During recent triage, we identified the need to mark an issue as related
to CI/testing, this adds that label.  We'll need to run the sync script
again.
=> Add a kind/ci label

jenkins/README.md
Update Jenkins document according to 
https://gerrit.nordix.org/c/infra/cicd/+/4213, which removes v1alpah2 integration CI support.
=> Update Jenkins doc

jenkins/scripts/files/run_integration_tests.sh
Due to the problem found in kind using local registry in case of local image patch testing, kind usage disabled temporarily, until fix found.
=> :bug: Temporarily disabling kind usage as management cluster

jenkins/scripts/files/run_integration_tests.sh
Remove v1alpha1 integration test caller since it going to be deprecated in [#292](https://github.com/metal3-io/metal3-dev-env/pull/292)
=> Remove v1alpha1 integration test caller

prow/config/config.yaml
Branch protection makes it so prow (tide) will not merge a PR unless a
set of requirement CI jobs passes.  We currently manage this manually
in github to ensure the functional CI jobs from jenkins passes.  This
PR moves the configuration of what jobs block PRs into this repo and
to be managed by prow.
All jobs that run by default (always_run: true) will now block by
default.  Jobs that run outside of prow (like jenkins) must be
explicitly listed in configuration.
We weren't actually blocking on any of the prow CI jobs before this,
which is one major improvement.  This also lets us manage another
aspect of our github org configuration through this repo.
=> prow: Add branch protection management

prow/config/config.yaml
This fixes branch protection settings for cluster-api-provider-metal3.
The previous configuration made master require both "test-integration"
and "test-v1a4-integration".  The requirements are the union of parent
and child lists, instead of only the child list.
Instead, we now specify the required contexts for this repo on a per
branch basis.
Reported-by: maelk <mael.kimmerlin@est.tech>
=> prow: Fix branch protection for CAPM3

jenkins/scripts/files/run_integration_tests.sh
Add ability to use local images of BMO & CAMP3 when CI is triggered from Metal3-dev-env repo or as master job.
=> Use local images of BMO&CAMP3 for CI

prow/config/config.yaml
Now that the tools are in place [1] we should run the job on every PR.
[1] https://github.com/metal3-io/baremetal-operator/pull/497
=> require the operator-sdk-generate job for baremetal-operator repository

prow/config/config.yaml
This reverts commit 2e57c4af8eeecb3b974cc58f4836950d57098166.
We need to wait for
https://github.com/metal3-io/baremetal-operator/pull/504 before making
this job required.
=> Revert "require the operator-sdk-generate job for baremetal-operator repository"

jenkins/jobs/integration_tests.pipeline, jenkins/scripts/fetch_logs.sh, jenkins/scripts/fetch_logs_clean.sh, jenkins/scripts/files/run_clean.sh, jenkins/scripts/files/run_fetch_logs.sh, jenkins/scripts/files/run_integration_tests.sh, jenkins/scripts/integration_test_clean.sh
This PR modifies the pipeline and the scripts running the metal3-dev-env integration tests to fetch the logs from all containers at the end of the run, they will be saved as artifacts for that run
=> jenkins: Add fetching container logs from metal3-dev-env

prow/config/config.yaml
We have created a new repo, ipam, for the ip address manager, this adds the jobs there. A renaming of the repo should probably be done, as this name was arbitrarily decided as a temporary solution to let the development of CAPM3 keep going.
=> Add prow jobs for IPAM repo

prow/config/config.yaml
This reverts commit be7f3e67d8ae6a242b625f074267bcc73b47d340.
=> Restore the operator-sdk-generate job on the baremetal-operator repository

prow/config/config.yaml
default_decoration_config has been deprecated according to the config
validation tool (make validate).  Replace it with the new equivalent
option.
=> prow: Update use of deprecated config entry

clusters/ci/imagepruner.yaml, prow/config/config.yaml, prow/manifests/deck-deployment.yaml, prow/manifests/hook-deployment.yaml, prow/manifests/horologium-deployment.yaml, prow/manifests/plank-deployment.yaml, prow/manifests/sinker-deployment.yaml, prow/manifests/statusreconciler-deployment.yaml, prow/manifests/tide-deployment.yaml
I haven't upgraded prow since it was deployed several months ago.  I now want to get upgrades automated.  This PR is the first step.  It adds a periodic job that automatically generates PRs with manifest updates.
Once this piece is working smoothly, I will add another job that automatically applies the updated manifests to the cluster after PRs merge that change them.
The PR also includes one other unrelated CI cluster manifest (ImagePruner) that I had sitting in my working copy.
=> Start working on Prow upgrades

jenkins/scripts/files/run_fetch_logs.sh
Following https://github.com/metal3-io/metal3-dev-env/pull/330 we can fetch the vm console logs as part of the log fetching process in the metal3-dev-env tests.
=> Jenkins, fetch m3-dev-env console logs during log gathering

jenkins/jobs/integration_tests.pipeline, jenkins/scripts/files/run_integration_tests.sh, jenkins/scripts/integration_test.sh
This adds `NUM_NODES `and `TESTS_FOR` variables that will be used in Metal3-dev-env for testing pivoting, upgrade and remediation tests in Metal3-dev-env.
=> Jenkins: Add conditions to trigger pivot/upgrade/remediation tests

jenkins/scripts/files/run_integration_tests.sh
Avoid building BMO image due to the time it requires during the
metal3-dev-env runs. Avoid building CAPM3 images if it is a PR
in metal3-dev-env. Keep building metal3-dev-env image for master
jobs
=> Jenkins: do not build BMO and CAPM3 images for each m3-dev-env PRs

jenkins/jobs/integration_tests.pipeline, jenkins/scripts/integration_clean.sh
to prevent collisions when two tests are started at the same time
=> Jenkins: use random characters in vm names

jenkins/jobs/integration_tests.pipeline
Increase timeout for feature tests to 10 hours since now the upgrade tests will also be running.
=> Increase timeout for feature test

prow/config/plugins.yaml
Prow was previously configured to use its default behavior of looking
at public membership of the metal3-io github org to determine who was
an allowed reviewer (who can /lgtm a PR).  This change switches to
using the OWNERS files in each repository, instead.
For more information, see:
- https://github.com/metal3-io/metal3-docs/pull/93
- https://github.com/metal3-io/metal3-docs/pull/94
=> prow: Use OWNERS file to determine reviewers

jenkins/scripts/integration_test.sh
Set ServerAliveCountMax to 10 for ssh connections to wait a bit more before ending the sessions.
=> Add ServerAliveCountMax for ssh connection

prow/config/config.yaml
After the CAPM3 v1a4 release, we have changed or main jobs to v1a4. We need to adapt the prow config to reflect the change in CAPM3
=> Update prow config for CAPM3 jobs

jenkins/scripts/integration_clean.sh, jenkins/scripts/integration_delete.sh, jenkins/scripts/integration_test.sh
This patch takes the volumes created in [airship-dev-tools/pull/210](https://github.com/Nordix/airship-dev-tools/pull/210)
in use, by cloning the volume and starting the VM in CI with the cloned base volumes
Related to this patch:
-  [airship-dev-tools/pull/219](https://github.com/Nordix/airship-dev-tools/pull/219)
=> ✨Add using volume instead of image to integration tests

jenkins/jobs/integration_tests.pipeline
Currently, integration CI is failing mostly due to the timeout. This is a temporary fix until we really find the reason for the CI to be slow.
=> Jenkins: Increase integration CI timeout

jenkins/jobs/integration_tests.pipeline
Revert https://github.com/metal3-io/project-infra/pull/143 as the timeout causing issue was fixed by https://github.com/metal3-io/baremetal-operator/pull/632.
=> Jenkins: revert #143

jenkins/scripts/files/run_integration_tests.sh
Centos based upgrade & feature tests are failing due to incorrect utilization of TESTS_FOR variable.
This should be merged after https://gerrit.nordix.org/c/infra/cicd/+/6021 gets in.
=> Jenkins: fix upgrade test caller

prow/config/config.yaml
Update the version of go used in the baremetal-operator jobs in
preparation for
https://github.com/metal3-io/baremetal-operator/pull/650
=> update go images for baremetal-operator jobs

jenkins/scripts/integration_clean.sh, jenkins/scripts/integration_delete.sh, jenkins/scripts/integration_test.sh
This PR only adds using Ubuntu volume instead of Ubuntu images in Jenkins, while Centos based setup remains same
=> Jenkins: Use Ubuntu volume instead of image

jenkins/scripts/integration_clean.sh
This PR fixes volume deletion name problem, where the cleanup job script looks for volumes starting with `ci-test-volume-` but volume names start with `ci-test-vm-` making unused volumes packed in CityCloud.
List of volumes in CityCloud is [here](https://citycontrolpanel.com/openstack#volumes)
=> Fix volume deletion

jenkins/scripts/integration_clean.sh
We are seeing an error while running [cleanup jobs](https://jenkins.nordix.org/view/Airship/job/airship_master_integration_tests_cleanup/851/console) in CI for volumes. Below provided is error from CI job console log:
```
Deleting executer volume <volume_id>.
Failed to delete volume with name or ID <volume_id>: Policy doesn't allow volume_extension:volume_admin_actions:force_delete to be performed. (HTTP 403)
1 of 1 volumes failed to delete.
```
However, normal deletion without `--force` works properly. 
Follow-up to #153
=> Remove --force delete from volume deletion

jenkins/scripts/integration_test.sh, jenkins/scripts/utils.sh
When test executor volume creation or resizing it fails, it will stay in an infinitive loop trying to create or resize volume. This PR avoids infinitive looping and adds retrying in case of above mentioned failures.
=> Add retry conditions to volume creation and resizing steps

jenkins/scripts/integration_delete.sh, jenkins/scripts/utils.sh
When resizing a volume, volume still goes into `error_extending` status and stays there due to the improper condition check. This PR fixes that, by checking if volume status contains the substring `error` and also adds 10s delay while deleting a volume for proper deletion.
=> Fix condition checking when volume status contains an error substring

jenkins/scripts/integration_test.sh
This PR fixes volume resizing when we are running feature tests. Currently volume is resized to 100GB for all tests, however feature tests need at least 300GB.
=> Fix volume resizing in case of feature tests

prow/config/config.yaml
This adds a new manifestlint job to the prow configuration so the
manifestlint.sh script gets triggered for every pull request in
BMO, CAPM3, IPAM, HWCC repos. The task of the manifestlint.sh is
to validate only core types based manifests within those repos and
report if they don’t match Kubernetes OpenAPI specification.
=> Add manifest linting job to prow as a new CI check

jenkins/scripts/files/run_integration_tests.sh
We are using CAPI release version 3.10 for upgrade test. This PR will enable to use the latest CAPI release.
=> CI: Run upgrade test with latest CAPI release.

jenkins/scripts/files/run_integration_tests.sh
We were disabling BASIC_AUTH and TLS for upgrade CI job. This PR will enable the setup.
=> Enable basic authentication and TLS for upgrade CI job.

prow/config/config.yaml
Bump the Golang version to [1.16](https://blog.golang.org/go1.16)
=> Bump the Golang version to 1.16

jenkins/jobs/integration_tests.pipeline
Feature tests CI jobs timeout is set to 10 hours, which is unnecessary.  In case of failed CI jobs, they are consuming resources in citycloud for longer period of time.  In successful run the CI jobs always are completed within 3 hours.  This PR will reduce the timeout to 3.5 hours.
=> Reduce feature tests CI timeout time.

jenkins/scripts/files/run_integration_tests.sh
These container images are defined in the metal3-dev-env repo
but currently aren't tested in CI, leading to potential regressions
such as https://github.com/metal3-io/metal3-dev-env/pull/609
We should always build/test these for metal3-dev-env CI, to catch
issues before changes to the Dockerfiles land.
=> Test sushy-tools/vbmc in metal3-dev-env CI

prow/config/config.yaml
We are making the ipam jobs optional temporarily since prow is WIP and we are relying on travis for the time being. 
Reference: https://github.com/metal3-io/ip-address-manager/pull/27
=> Remove IPAM jobs from prow temporarily

prow/config/config.yaml
Since prow job is WIP, we are making the jobs for CAPM3 and Metal3-dev-env 
optional temporarily. Once prow is working, we can remove this tag
=> Make prow jobs for CAPM3 and Metal3-dev-env optional

jenkins/scripts/files/run_integration_tests.sh
In order to reduce dependency on upstream services (e.g. in the event of network degradation between Sweden and US West, where the default Ironic Python Agent tarball is hosted), set IPA_BAREURI to download IPA from Nordix Artifactory in CI. 
This has the added benefit of potentially reducing build times, because we'll be downloading from the same infrastructure on which the CI is hosted.
=> Get Ironic Python Agent from Artifactory

jenkins/scripts/files/run_fetch_logs.sh, jenkins/scripts/files/run_integration_tests.sh
This PR 
1. makes sure that when we fetch the container logs we also take the dead container logs since those can also give information about why a container might be failing. Currently we always have to login to the
CI vm to find out whats happening in-case an ironic container did not start properly.
2. Removes unnecessary image building for CAPM3 and BMO on a Project-infra integration test.
=> Fetch also exited container logs

prow/config/plugins.yaml
We have duplicated [lines of code](https://github.com/metal3-io/project-infra/blob/master/prow/config/plugins.yaml#L47-L65) for enabling external plugin needs-rebase. This patch removes the duplication for that.
=> Remove duplication in external plugins

prow/config/config.yaml
I think even in the previous prow setup we weren't using autobump, and by looking at [past PRs](https://github.com/metal3-io/project-infra/pulls?q=is%3Apr+author%3Ametal3-io-bot+is%3Aclosed), it seems automatic image updates didn't go well. I've also looked at other repos like KubeVirt, Jetstack, Falco and it seems they are also doing image updates manually.
I can take care of updating those images from time to time. The good thing from doing updates manually is sometimes we might need to make some configuration changes in our manifests/config/plugins files before taking the latest images.
=> Don't use prow image autobump

jenkins/jobs/integration_tests.pipeline
When trying to add scale in and node reuse feature tests to feature test framework, [tests are timing out ](https://jenkins.nordix.org/job/airship_metal3io_metal3_dev_env_feature_tests_ubuntu/267/)due to the added features are time consuming(includes upgrading). For that reason, this PR increases time out for running feature tests in CI from 3.5h to 5h.
=> Increase feature tests timeout in CI

prow/config/plugins.yaml
As a community-driven open source project, we want all PR authors to
be subject to the same review requirements. That includes requiring
folks who have approval rights to have 2 reviews, including a review
from another approver. To achieve this, enable the `approve` plugin
setting `require_self_approval` to require explicit approval of PRs.
At the same time, ensure that all PRs are examined by someone with
approval permission by explicitly disabling `lgtm_acts_as_approve`.
Discussion on the mailing list: https://groups.google.com/g/metal3-dev/c/H9rR-mjgJ5s
=> disable automatic self-approval and ensure 2 lgtm does not approve

jenkins/scripts/files/run_integration_tests.sh
We are moving Metal3-dev-env and sushy-tools Dockerfiles to ironic-image repo. This is to update the vars of local image.
=> Move sushy-tools & vbmc to ironic-image repo

jenkins/scripts/files/run_fetch_logs.sh
Configuration is written to ~/.cluster-api, edited and reapplied during the upgrade tests. It would be useful to examine the contents when debugging.
=> Add .cluster-api config to fetch logs tarball

prow/config/config.yaml
Related JJB jobs in gerrit:
Removing v1a3 jobs: [9034](https://gerrit.nordix.org/c/infra/cicd/+/9034)
Adding v1a5 jobs: [9024](https://gerrit.nordix.org/c/infra/cicd/+/9024)
=> ✨ Add required test triggering contexts for v1a4 and v1a5

prow/config/config.yaml
Since we keep running only v1a4 changes for now, and current configurations in CAPM3/IPAM expects to run v1a5 jobs with different keywords, this needs an update. 
Related jjb patch: [9097](https://gerrit.nordix.org/c/infra/cicd/+/9097)
=> 🐛 Change status checks for master and release branches in CAPM3/IPAM

prow/config/config.yaml
This PR changes integration test status check
1. test-integration points to master
2. test-v1a4-integration points to release branches
for CAPM3 and IPAM
=> Change integration test status check

jenkins/scripts/files/run_integration_tests.sh
Enable building local images of CAPM3 & IPAM temporarily to be able to test changes related to CAPI v1alpha4 from within metal3-dev-env repository. This should be reverted once CAPI v1alpha4 related patches land in IPAM and CAPM3 repositories.
=> Build local images of CAPM3 and IPAM in dev-env patches

jenkins/scripts/files/run_integration_tests.sh
Jenkins: Revert https://github.com/metal3-io/project-infra/pull/209, as exporting vars from project-infra causes unbound variables issue.
=> Jenkins: Revert #209

prow/config/config.yaml
The registry path for DockerHub https://registry.hub.docker.com/v2/ returns a 404. Docker/Podman make a GET request to this path before pulling the image, and they're failing at this step. Whether DockerHub have deprecated or changed the behaviour of their registry is unclear.
Updating the paths to docker.io resolves this issue and allows Docker image pulling once more. This should fix the Prow jobs that are failing markdownlint.
Additionally, images which were being pulled from DockerHub have now been explicitly marked as being pulled from docker.io.
=> Update DockerHub registry path

jenkins/scripts/files/run_integration_tests.sh, jenkins/scripts/integration_test.sh
Run the CAPM3 e2e tests on Jenkins.
Relies on [CAPM3#229](https://github.com/metal3-io/cluster-api-provider-metal3/pull/229)
=> Handle e2e tests in integration test scripts

jenkins/scripts/integration_test.sh
Currently there are 'no space left on device' failures, e.g. https://jenkins.nordix.org/job/airship_metal3io_capi_m3_e2e_test_ubuntu/4/console
=> Use larger VM volume for e2e tests

jenkins/scripts/files/run_integration_tests.sh
Change the 'yellow' color used in Ansible changed tasks to something more readable.
=> Make Ansible colors in Jenkins readable

jenkins/jobs/integration_tests.pipeline
Test time has increased since fixing the bug where an even number of replicas were created. Additionally, minikube may take some time to start in the retry loop.
=> Increase feature test timeout to 6 hours

jenkins/scripts/files/run_fetch_logs.sh
When Ironic is running outside of the cluster, i.e., as docker containers, initial logs of the containers get lost after pivoting to the target cluster. Currently we are fetching Ironic container logs at the end of the CI run, when we are pivoted back to the source cluster and when Ironic containers are recreated. Since Ironic is re-created, we are losing initial logs of Ironic containers, for example when Ironic nodes go from registering to ready state, which happens only on the source cluster. Losing those logs will only make it confusing for someone debugging the Ironic.
This patch copies those fetched logs from `/tmp` to the CI output. See the related slack discussion [here](https://kubernetes.slack.com/archives/CHD49TLE7/p1627462885343400).
Related PR in dev-env: …
=> Fetch Ironic container logs before pivoting

jenkins/jobs/integration_tests.pipeline
The `e2e-tests` are equivalent to the feature-tests then once we have all `e2e-tests` in place they will need almost the same duration as feature-tests (more than 4h). 
Currently the `e2e-tests` timeout is the default 1 hour and 30 minutes, for this reason this PR increases the e2e-test timeout to 6 hours.
=> Increase e2e-tests timeout

jenkins/scripts/files/run_integration_tests.sh
Instead, IPA is bundled with the image. We don't need to run the ipa-downloader again, so set the IPA_DOWNLOAD_ENABLED environment variable to "false" to skip the download.
TODO: Run integration tests after https://github.com/metal3-io/baremetal-operator/pull/957 is merged, and check that ipa-downloader isn't run in the build output.
=> Don't download IPA in integration tests

jenkins/scripts/files/run_integration_tests.sh
This will help to run v1a4 with k8s version 1.21.2 and v1a5 with k8s version>= 1.22
=> Set Kubernetes Version to v1.21.2 for v1a4 jobs

jenkins/scripts/integration_test.sh
While passing variables to metal3-dev-env with file vars.sh, it keeps variables which were passed through Jenkins Pipeline.
=> append variables to vars.sh file without emptying the file 

jenkins/scripts/files/run_integration_tests.sh
IMAGE_LOCATION and IMAGE_NAME vars are needed to download temporary created image from artifactory for airship-dev-tools repo`s integration test
=> exports IMAGE_LOCATION and IMAGE_NAME variables for airship-dev-tools integration test

prow/config/config.yaml
1. Replace `gcs_configuration` with s3 bucket
2. Fix `prowjob_namespace`  to be `prow` instead of `default`
=> Bug: fix incorrect namespace in the prow configMap

prow/manifests/starter.yaml
We don't setup prometheus, so there is no benefit of passing these
flags to enable metrics collection.
=> Don't enable push-gateway in ghProxy

jenkins/scripts/integration_test.sh
Even when we have a PR not for main branch (i.e. for release branch) we are checking out in main branch instead of the target branch. Apparently, the` REPO_BRANCH ` does not need to be defaulted to `master`. REPO_BRANCH is based on `ghprbTargetBranch` Jenkins variable. And `ghprbTargetBranch` is populated through JJB. This PR removes the checking as  tested in #266
=> Jenkins: remove conditionals around REPO_BRANCH

prow/config/config.yaml
Since we migrated to v1b1 now, we should make v1a5 tests as required in m3-dev-env repo replacing v1a4, where latter can be triggered case by case scenarios and we keep only master jobs to watch it.
=> Make v1a5 centos job required in m3-dev-env repo

jenkins/scripts/integration_test.sh
The e2e master tests for v1alpha5: [master_e2e_v1a5_test_centos](https://jenkins.nordix.org/view/Airship/job/airship_master_e2e_v1a5_test_centos/) [master_e2e_v1a5_test_ubuntu](https://jenkins.nordix.org/view/Airship/job/airship_master_e2e_v1a5_test_ubuntu/) are not running on FRA1 region
=> Add release master JJBs to FRA1

prow/config/external-plugins/cherrypicker_deployment.yaml, prow/config/external-plugins/cherrypicker_service.yaml, prow/config/plugins.yaml
This adds cherry-pick external plugin.
Short description from https://prow.k8s.io/plugins
_"The cherrypick plugin is used for cherrypicking
PRs across branches. For every successful
cherrypick invocation a new PR is opened
against the target branch and assigned to
the requestor. If the parent PR contains
a release note, it is copied to the cherrypick
PR."_
=> Prow: add cherrypicker external plugin

prow/Makefile, prow/manifests/labels_cronjob.yaml
This patch moves label synchronization CronJob to default
namespace, thus updates the Makefile entry related to it.
Also, it makes it to reuse the existing github-token Secret,
and bumps the label synchronization image to
[v20211111-bce61c7c4a]( gcr.io/k8s-prow/label_sync:v20211111-bce61c7c4a).
=> Re-configure label synchronization CronJob

prow/config/plugins.yaml
This ensures that whenever a patch that modifies labels.yaml gets
merged, label-config live configMap gets updated by config updater.
=> Add labels.yaml to config_updater

jenkins/scripts/files/run_fetch_logs.sh
We have been getting this issue but didn't notice it because the script
that runs it doesn't request to print out the commands.  I spotted this
issue in https://github.com/metal3-io/metal3-dev-env/pull/863, while adding `-x` flag to set. 
```
error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
template was:
{.items[0].metadata.name}
object given to jsonpath engine was:
map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```
=> Fix a bug with jsonpath during log fetching

jenkins/scripts/bare_metal_lab/files/config.sh, prow/config/config.yaml
This PR prepares the prow config for BMO main branch switch. Mainly this PR adds the branch monitoring for BMO in prow config. Currently it monitors two branches main and master. Once main is the default branch, master would be removed.
=> Prepare for BMO main branch switch

prow/config/config.yaml
Skip CI jobs that are not needed when only e.g. docs or OWNERS files are
modified in the PR.
=> Avoid unnecessary CI jobs

jenkins/scripts/integration_test.sh
This commit was created because out of space erros have been
noticed during CI job execution.
=> Increase VM storage volume size

jenkins/scripts/bare_metal_lab/deploy-lab.yaml
This PR adds ansible task which shrinks size of syslog before starting the test in BML .
In Bare metal lab syslog file size sometimes increases up to 20-30 Gb per day. Before running tests on BML we should shrink the size of syslog file in order to avoid failure due to shortage of space
=> Shrink syslog file size in BML 

prow/config/config.yaml
quay image [quay.io/metal3-io/capm3-unit](https://quay.io/repository/metal3-io/capm3-unit) used in CAPM3 is now built with go version v1.17 after https://github.com/metal3-io/cluster-api-provider-metal3/commit/fa03e148c0e84fcc18f06df4adc93771afa2a005 That same image also used for checking prow jobs in release-0.5/0.4 branches of CAPM3, which should not be the case, because golang version being used in those branches is v1.16, and for that reason we have to have new presubmit jobs with proper quay images ([quay.io/metal3-io/capm3-unit:release-0.5](quay.io/metal3-io/capm3-unit:release-0.5)) / ([quay.io/metal3-io/capm3-unit:release-0.4](quay.io/metal3-io/capm3-unit:release-0.4)) and this PR adds them.
=> ✨Add presubmit prow jobs for CAPM3 release-0.5/0.4 branches

prow/config/config.yaml
1. Switch to `docker.io/golang` image in CAPM3 and IPAM from `capm3:unit` image.
2. Remove optional flag from Prow jobs, since they have to run on every PR and it
was temporarily added while Prow was down.
3. Add `gofmt`, `unit`,  `govet`, `generate` jobs to IPAM release-0.0 & release-0.1
branches.
=> Switch to docker.io/golang:1.16 image in capm3 tests

prow/config/config.yaml
Increase frequency of running go based CI jobs.
We should be more careful to when not to run go based
prow jobs. We recently faced a PR which didn't touch
`.go `file, so gofmt test didn't run but that change made
existing `.go` files to fail passing go fmt. As such, make it
more strict when the jobs should not run.
=> Increase frequency of running go based CI jobs 

jenkins/README.md, jenkins/scripts/bare_metal_lab/deploy-lab.yaml, jenkins/scripts/files/run_integration_tests.sh, jenkins/scripts/integration_clean.sh, jenkins/scripts/integration_delete.sh, jenkins/scripts/integration_test_clean.sh
This PR removes master references. It doesn't cover all the cases. Followup PRs would be needed to remove all the references once other repos in metal3 also introduce the same.
=> Remove master reference in BML pipeline and comments

jenkins/README.md, jenkins/jobs/bml_integration_tests.pipeline, jenkins/jobs/integration_tests.pipeline, jenkins/jobs/integration_tests_clean.pipeline
We have now switched to main branch as default branch
in project-infra. This patch ensures that references to this
repo also points to main branch in various scripts.
=> Switch to main in project-infra references

jenkins/jobs/bml_integration_tests.pipeline, jenkins/scripts/bare_metal_lab/README.md
The builds in BML always use the same machine so we cannot allow multiple builds to run at the same time.
=> Disable concurrent builds in BML

jenkins/scripts/integration_delete.sh, jenkins/scripts/integration_test.sh, jenkins/scripts/utils.sh
This is to avoid collisions when multiple jobs would happen to select
the same IP. If each job creates its own IP we get no collisions.
=> Create/delete floating IP in Fra1

jenkins/scripts/files/run_fetch_logs.sh
When e2e tests are run, the resources in the cluster are dumped to the tested_repo/_artifacts directory. These artifacts will now be included in the Jenkins artifact logs tarball so that resources in e2e jobs can be inspected after the job has ended.
=> Add e2e tested_repo _artifacts dir to logs tarball

jenkins/scripts/integration_test.sh
I made a logic error in the last PR. It should be setting these variables only *if they have some value*. If they are unset or empty string we should ignore them to allow default values to be used.
/hold
Don't merge this until [this](https://gerrit.nordix.org/c/infra/cicd/+/12038) is in so we can properly test it.
=> Fix unbound variable use logic

jenkins/scripts/files/run_integration_tests.sh
add export KUBERNETES_VERSION for airship dev tools integration tests.
We need to export KUBERNETES_VERSION variable for airship integration tests.
=> Add export K8s  version for airship integration tests

prow/config/plugins.yaml, prow/manifests/starter.yaml
Based on my investigation, we should be able to get the advantage of using `transfer-issue` plugin by just adding it to the list of plugins and metal3-io-bot should be able to interpret it as intended, unless I missed some configuration part.
**Workflow:**
Source: https://docs.google.com/document/d/1uqKI5QEAh2fnq7LRRz-2Mhf-jInIpuiAUnPow36jCVU/edit
**Usage within the same org commented on the issue:**
`/transfer <TARGET_REPO>` or `/transfer-issue <TARGET_REPO>`
i.e, transferring issue from cluster-api-provider-metal3 repo to ip-address-manager repo should be done using:
`/transfer ip-address-manager`
Fixes: #234
=> ✨ Add transfer-issue plugin to Prow

prow/config/labels.yaml, prow/config/plugins.yaml
Allow setting needs-triage label on GitHub issues. This will tag
issues so that community is aware and takes some actions on them
during next triage meeting. Once action is taken, triage/foo should
be set indicating the triage status of the issue. Possible options
triage/unresolved, triage/not-reproducible, triage/duplicate,
triage/needs-information, triage/accepted.
=> Allow adding triage labels on issues across Metal3.io

prow/config/config.yaml
Whenever there is a change in files (`config.yaml, labels.yaml or plugins.yaml`) under `prow/config` folder, configmap will be updated in the prow cluster. Current configmap for config.yaml looks like as below:
```
`ubuntu@prow-metal3:~/project-infra/prow$ kubectl get cm config -n prow -oyaml
apiVersion: v1
data:
config.yaml: "prowjob_namespace: prow\npod_namespace: test-pods\nlog_level: debug\n\n#
Sinker configurations (for cleanup)\nsinker:\n  resync_period: 1m\n  max_prowjob_age:
4h\n  max_pod_age: 30m\n  terminated_pod_ttl: 2h\n\nplank:\n  job_url_prefix_config:\n
\   \"*\": https://prow.apps.test.metal3.io/view/\n  report_templates:\n    '*':
>-\n        [Full PR test history](https://prow.apps.test.metal3.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with
index …
```
=> 🐛 Prow: Remove additional blank space from prow config file

jenkins/jobs/integration_tests.pipeline, jenkins/scripts/files/run_integration_tests.sh, jenkins/scripts/integration_test.sh
This PR exports UPGRADE_TEST that should be used in the CAPM3 e2e test to select the upgrade test
=> 🌱 Add UPGRADE_TEST var export for e2e upgrade tests

prow/config/plugins.yaml, prow/manifests/starter.yaml
We have enabled needs/triage label earlier in https://github.com/metal3-io/project-infra/pull/307 but that commit misses adding `require-matching-label` plugin to the list of plugins used across Metal3.io repos. This adds that plugin to the list.
=> Prow: Add missing require-matching-label plugin to plugins list

jenkins/README.md, jenkins/scripts/bare_metal_lab/README.md, jenkins/scripts/bare_metal_lab/deploy-lab.yaml, jenkins/scripts/files/run_integration_tests.sh
Where credentials, repo names and JJB paths are mentioned in
project-infra, where airship was referenced, metal3 is now used instead.
TODO before merging:
* Rename airship-dev-tools -> metal3-dev-tools
* Rename airship -> metal3 in JJB directory and job names
* Update Nordix Jenkins view to Metal3 (referencing metal3 jobs)
Remaining to fix:
* airshipci username in images
* Environment variables in scripts named AIRSHIP
@kashifest @furkatgofurov7
=> Rename airship to metal3 in repos and jjb

jenkins/jobs/integration_tests.pipeline, jenkins/jobs/integration_tests_clean.pipeline, jenkins/scripts/files/run_fetch_logs.sh
This will swap to use the metal3ci user in the image instead of the airshipci user. After this, other pipelines will be updated and then the old airshipci user can be removed from use.
=> Use metal3ci user for CI runs

jenkins/scripts/bare_metal_lab/templates/bmhosts_crs.yaml.j2
Since the node 4 of BML is facing a hardware issue that blocks it from turning on, using node 6 is a workaround.
=> Change the BML to use node 6 as a provisioned node

jenkins/scripts/utils.sh
Network names was renamed in the CityCloud infra, where the Jenkins tests run.
Renaming it here too.
=> Rename prefix of OpenStack networks from airship to metal3

jenkins/README.md, prow/config/config.yaml
This makes the required status checks symmetrical, i.e. they always include
"ubuntu" or "centos" in the name instead of taking the absense of
"centos" as "ubuntu". Spelling out the OS makes it easier to understand
and enables parametrization in JJB.
=> Include ubuntu in status checks

jenkins/scripts/files/run_integration_tests.sh
It used to check for feature_tests or feature_tests_centos, but now it
is in fact feature_tests_ubuntu or feature_tests_centos.
This change in the value was caused by https://gerrit.nordix.org/c/infra/cicd/+/12409 and I didn't realize it.
=> 🐛 Fix TESTS_FOR value check for ubuntu feature tests

jenkins/scripts/integration_test.sh, jenkins/scripts/utils.sh
This is an attempt to work around the "no space" issue that is caused by a failed filesystem resize.
You can see the retry working in this run: https://jenkins.nordix.org/job/metal3_project_infra_v1a5_integration_test_centos/38/console
Unfortunately it failed later while deprovisioning, but everything else worked. It is quite hard to reproduce the issue so I have not tried to get another successful run with the retry.
I used a temporary commit for running in Fra1 to reproduce it more easily. This is now removed.
=> Retry openstack server creation if unhealthy

OWNERS
Following the community principle of adding reviewers, this PR adds Lennart Jern (@lentzi90 ) as a reviewer since he has 10 commits in this repository.
List of his commits in the repo: https://github.com/metal3-io/project-infra/commits?author=lentzi90
=> 📖 Add Lennart Jern as reviewer

.github/workflows/yamllint.yaml, .yamllint.yaml, jenkins/scripts/bare_metal_lab/deploy-lab.yaml
Currently we don't lint YAML files. As a result, sometimes we see
issues with some YAML code being merged and the issue is identified
later on. Example, trailing spaces which might breake the
configuration file of Prow.
This patch adds yamllinter based GitHub action so that we verify
correctness of YAML files on every pull request submission, before
landing on the main branch. As a start, trailing space, key-duplicate
and truthy rules are enabled, and the list can be extended based on
the need.
Fixes: https://github.com/metal3-io/project-infra/issues/322
=> Add linter CI for YAML files

jenkins/jobs/integration_tests.pipeline, jenkins/scripts/skip_integration_test.sh
This PR introduces a possibility to skip running integration tests on PRs opened in Metal3 repositories, where the patch contains **ONLY** `.md` file extension or `OWNERS` file type changes. 
To clarify, all PR's in repositories still would require (if configured so) to trigger required/desired integration test triggers, since that is mandated not only in the Jenkins configuration file in this repo but also on all Metal3 Repos' GitHub settings, where certain integration test is marked as 'required'. However, time + resources can be saved, as we skip:
- creating a VM to run integration tests
- fetching logs and archiving them
- cleaning up the environment (make clean)
- deleting used resources (VM, port)
Main jobs using the same pipeline should also keep working as is after these changes, …
=> ✨ Skip running integration tests on markdown and OWNERS files in PRs

jenkins/scripts/skip_integration_test.sh
This PR changes the way how we find out the changes made in the PR when custom skipping integration tests are used. The problem with the current implementation is, it does not consider the case, where for example the PR branch opened some time ago falls behind the origin branch it checked out (the branch is ahead of its checked out branch X commits and behind it, Y commits), then, git diff outputs all the changes that went in with Y commits since we are doing comparison from current branch against origin/{default_branch}. 
Now, this is done in a way that we look for all changes on the current branch since the branch start point as [here](https://stackoverflow.com/questions/29810331/is-there-a-quick-way-to-git-diff-from-the-point-or-branch-origin).
=> Change git diff logic in custom skip integration script

jenkins/scripts/integration_test_env.sh
Use upstream quay and docker hub while we wait for Nordix registry to be back up again.
=> Temporary fix while Nordix registry is down

jenkins/scripts/bare_metal_lab/deploy-lab.yaml, jenkins/scripts/bml_integration_test.sh
Currently, triggering the BML test on metal3-dev-env can only test the main branch of metal3-dev-env. This PR makes it test the patch in the PR where the test is triggered.
=> Run BML test with updated code on metal3-dev-env.

jenkins/scripts/integration_test.sh, jenkins/scripts/utils.sh
The issue should now be fixed and we can rely on checking cloud-init status instead of comparing filesystem and disk sizes. The retry for server creation was also removed since we do not expect there to be issues that can be solved by recreating the server anymore.
=> Remove workaround for "no-space" issue

prow/manifests/starter.yaml
Recent releases starting from docker `RELEASE.2022-04-30T22-23-53Z` have dropped the support for the Azure gateway mode. And for those who are interested in continuing the usage of Azure gateway mode using releases prior to `RELEASE.2022-04-30T22-23-53Z` is suggested in https://github.com/minio/minio/issues/14331#issuecomment-1058639010. As such, we are rolling back the image version from being latest to the `RELEASE.2022-04-29T01-27-09Z`, which is the latest&last release before the drop of the Azure gateway mode support. 
Also changed the image pull policy to be the `IfNotPresent` so that deployment doesn't try to pull the image from the internet and instead uses that one available locally, which is good enough for our case.
=> Fix MinIO image to RELEASE.2022-04-29T01-27-09Z

jenkins/scripts/integration_test_env.sh
When testing from` dev-env`, e2e should find it cloned in `tested_repo` instead of cloning it under `/opt/metal3-dev-env`
e2e clone dev-env here https://github.com/metal3-io/cluster-api-provider-metal3/blob/62562ec2522e3c4afa541cc75b1e9c111263a120/scripts/ci-e2e.sh#L19
=> Exporting M3_DEV_ENV_PATH to e2e

jenkins/scripts/files/run_integration_tests.sh
[BML tests](https://jenkins.nordix.org/view/Metal3%20Main/job/metal3_main_bml_integration_tests_centos/) in CI have been failing for some time and the tests we have done show that either introduction of CentOS9 stream: https://github.com/Nordix/metal3-dev-tools/commit/0d3e5cc313999e95e6a8e71842aafcd942ee0b48 or cloud-init changes: https://github.com/Nordix/metal3-dev-tools/commit/c5213dcd4582c6cb15d1873df70d8494a7a2c59f related to centos node image buildings, OR a combination of both, might have broken it. See the list of different tests run using different node images here: https://github.com/metal3-io/project-infra/pull/377#issuecomment-1128135511. For now, we can pin the node images used in BML to get the CI going.
=> Pin node image to be used in BML to CentOS8 Stream k8s v1.23.3

jenkins/scripts/integration_delete.sh
This commit makes the Fra1 floating IP deletion command a non
blocking action. This change was needed because there could be
provider side issues that might block deltion or there could be no
IP to delete and that would also cause an error response that would
break the VM deletion workflow.
=> Handle floating ip deletion error

jenkins/scripts/files/run_fetch_logs.sh, jenkins/scripts/files/run_integration_tests.sh
The condition `'[' cluster-api-provider-metal3 == 'cluster-api-provider-*' ']'`  [here](https://github.com/metal3-io/project-infra/blob/5ae9c8bcaccfb092350301c35dd7f446478c96de/jenkins/scripts/files/run_integration_tests.sh#L87)  was resulting in `false` while it should be `true`  and this because the pattern matching works only with double brackets so we need to use double `[[` instead of` [ `
Also this PR add the correct path to fetch logs when the e2e triggered from other repos
=> Fix fetching e2e logs

jenkins/scripts/files/run_clean.sh, jenkins/scripts/files/run_integration_tests.sh, jenkins/scripts/integration_test_clean.sh, jenkins/scripts/integration_test_env.sh
This PR fixes the issue : `/tmp/run_clean.sh: line 19: pushd: metal3: No such file or directory` when running e2e from capm3 repo
=> Fix capm3 cleaning issue

jenkins/scripts/files/run_integration_tests.sh
When running integration tests from capm3 the capm3 folder is cloned instead of dev-env
=> Fix running integration tests from capm3

jenkins/scripts/bml_integration_test.sh
There was no verbosity at the beginning of the BM deployment. This will help us to debug the test.
=> Add verbosity to bm lab integration test

jenkins/scripts/bare_metal_lab/templates/bmhosts_crs.yaml.j2
changing eselda13u31s03.est.lan to eselda13u31s03. Recently BML main jobs are failing due to regex complaining about the provider ID format which containe BMH name. This PR attempts to simplify BMH name to avoid having special characters like `.` in the name. '
=> Update the name of BMHs in CRs

jenkins/scripts/bare_metal_lab/deploy-lab.yaml, jenkins/scripts/bml_integration_test.sh, jenkins/scripts/files/run_integration_tests.sh
Previously we always cloned metal3-dev-env to the same folder when setting up BML, but the actual test uses different folders (tested_repo or metal3) depending on where it is triggered from.
=> BML: Clone metal3-dev-env to correct folder

jenkins/scripts/files/run_integration_tests.sh
the script writes `'null'` in the vars file when ginkgo_focus is undefined
=> Fix ginkgo_focus null string value

jenkins/scripts/files/run_integration_tests.sh, prow/config/config.yaml
- Currently CAPI clusterctl for v1alpha4 doesnt support 1.24.x due to the removal of the master taint. Until that is fixed upstream we need to run v1a5 with 1.23.x only.
- Remove master reference for m3-dev-env. Master branch for this repo has been removed.
=> Fix k8s version to 1.23.x for v1alpha5

jenkins/scripts/bare_metal_lab/deploy-lab.yaml
Previously we just checked out the updated branch. This always checks out the target (metal3-dev-env main) and then merges the updated repo/branch with it if there are differences.
=> BML: Merge the updated repo/branch with the target

prow/config/config.yaml
Configuration for enabling integration tests in the mariadb-image repo landed a long time ago, but it was missing to configure branch name for the repo, and this should fix it.  
See: https://github.com/metal3-io/mariadb-image/pull/2
=> 🐛 Prow: Add missing branch name configuration for mariadb-image repo

prow/config/config.yaml
Since CAPI has stopped supporting CAPI v1a4 which is equivalent to CAPM3
v1a5, it doesnt make any sense to keep testing v1a5/release-0.5 branch
as a required test. We are not dropping support yet but perhaps it
should not run as a required test on dev-env PRs.
=> Add main branch centos test as required for metal3-dev-env

prow/config/config.yaml
also drop prow jobs for IPAM release-0.0 since CAPM3 release-0.4 jobs were removed in https://github.com/metal3-io/project-infra/pull/416/files due to the support for CAPM3 v1a4 API.
=> 🐛 Use go1.17 for release-1.1 branch ProwJobs same as for main branch

jenkins/scripts/integration_delete.sh
When running tests (e2e) in Fra1 region, orphaned floating IP deletion succeeds only to delete a single floating IP and leaves out other IPs if there are bunch of them. We have seen these when we exhausted floating IPs in jobs: https://jenkins.nordix.org/job/metal3_keep_capm3_main_e2e_test_centos/13/console
Log from CI when floating IP deletion happens:
```
Running in region: Fra1
The option [tenant_id] has been deprecated. Please avoid using it.
Deleting executer floating IP da6e3ada-5ea9-4b58-b707-9f34d983c5aa.
The option [tenant_id] has been deprecated. Please avoid using it.
Executer floating IP da6e3ada-5ea9-4b58-b707-9f34d983c5aa is deleted.
The option [tenant_id] has been deprecated. Please avoid using it.
The option [tenant_id] has been deprecated. Please avoid using it.
Failed to …
```
=> 🐛 Properly delete all orphaned floating IPs from Fra1 region

jenkins/scripts/integration_test.sh
Fix for pipeline part is [here](https://github.com/Nordix/metal3-dev-tools/pull/580)
This PR fixes receiving IMAGE_NAME and  IMAGE LOCATION variables from pipeline for metal3 dev tools integration tests. Metal3 dev tools integration tests are not using temporarily built node image, but  default node image. Cause of the problem is IMAGE_NAME and iMAGE_LOCATION variables are not passed to the tests properly. This issue started appearing after we randomized the vars.sh file name [here](https://github.com/metal3-io/project-infra/blob/ef01400cb9c069290865fa01bd7e08b218c84499/jenkins/scripts/integration_test.sh#L129)
=> Fix receiving variables from dev tools integration tests pipeline

jenkins/scripts/integration_test_env.sh
For all other tests BMOBRANCH will be set as BMORELEASE once https://github.com/metal3-io/metal3-dev-env/pull/1072 PR lands
=> Set main as BMOBRANCH for main branch periodic test

prow/config/labels.yaml
Add lifecycle/frozen lable to indicate that an issue or PR should not be auto-closed due to staleness.
/cc @Rozzii
=> Prow: add lifecycle/frozen label

jenkins/README.md, prow/config/config.yaml
and also update dead links in the README
/hold
Prerequisites before taking this change in:
- release-1.2 branches created in both CAPM3/IPAM repos and new minor release: v1.2.0 is cut
- https://gerrit.nordix.org/c/infra/cicd/+/15169 needs to be merged
- https://github.com/metal3-io/metal3-dev-env/pull/1077 needs to be merged
After it lands:
- `required_status_checks` configurations in CAPM3/IPAM release-1.2 branches, in dev env main branch have to be configured 
- https://github.com/metal3-io/cluster-api-provider-metal3/pull/730
=> 🌱 Add release-1.2 CAPM3/IPAM branch configurations

prow/config/config.yaml
Bump golang image to v1.18 for main branch of different repositories in prow test
=> Bump golang image to v1.18 for main branch of different repositories

prow/config/plugins.yaml
also remove archived `metal3-io/cluster-api-provider-baremetal` from the list
=> 🌱 Add missing IPAM repo to plugins repos list

jenkins/scripts/integration_test_env.sh
This PR also noticed that the comment that we are not building BMO image is incorrect since we were. So since we were building CAPM3 and BMO images already for peiodic tests, this PR also adds the option to build IPAM image locally for periodic tests.
=> Fix BMOBRANCH=main only for main periodic test

prow/config/config.yaml
Depends on https://github.com/metal3-io/ironic-ipa-downloader/pull/37 merged first, or it'll block all PRs for ironic-ipa-downloader.
=> prow: add shellcheck test for ironic-ipa-downloader

jenkins/scripts/integration_test_env.sh
We were wrongly checking against REPO_BRANCH var since REPO_BRANCH refers to dev-env branch not the branch of CAPM3. We should check against CAPM3RELEASEBRANCH to make sure if the periodic test is running against main branch or release branch
=> Fix BMOBRANCH export

jenkins/scripts/bare_metal_lab/default_vars/vars.yaml, jenkins/scripts/bare_metal_lab/deploy-lab.yaml
This configures DNSMasq to ignore DHCP requests from unknown hosts in the BML. The idea is that this allows manual testing in the BML using the backup jumphost and spare hosts without interfering with the CI. So to be clear, the idea is not to run multiple CI jobs in parallel in the BMl.
Related to: https://github.com/metal3-io/metal3-dev-env/pull/1100
=> Support multiple instances in BML

prow/config/config.yaml
Use markdownlint image 0.12.0 pinned by SHA instead of latest.
In markdownlint 0.12.0 unordered lists are required to have 3 space prefix, while 0.11.1 needed only 2. This is due Kramdown dependency. This behavior changed and broke the markdown validations, preventing contributions, thanks to "latest" tag.
All of the Metal3 repositories (except one, PR pending) markdown files and their hack/markdownlint.sh validators have been fixed, and prow need to be up to date as well.
In addition, dependencies should be pinned by SHA, to guard against unintended changes via tag update. This also makes OpenSSF Scorecards happier.
=> Bump markdownlint to v0.12.0 and pin sha digest

prow/config/config.yaml
After all the repositories prow manages are updated and fixed to pass on shellcheck 0.9.0, we can merge this update to use the latest shellcheck.
/hold
until the other PRs are in.
=> prow: upgrade shellcheck to 0.9.0

jenkins/scripts/files/run_integration_tests.sh
We have a fix to Centos 9 issue in bml [here](https://github.com/metal3-io/metal3-dev-env/pull/1131), unpining node image for bml
=> Unpin node image for bml

prow/config/config.yaml
kubeval is not maintained anymore, and suggest moving to kubeconform. Change manifestlint.sh to use kubeconform.
Pin kubeconform image with a version and a digest.
Fix indentation of prow config.
=> move from kubeval to kubeconform

.github/workflows/yamllint.yaml
Set top-level permissions to read.
Pin actions by a sha.
=> .github: secure github actions

jenkins/README.md
The jenkins doc had wrong trigger command to keep the vm after integration test. This PR will update and fix those command.
=> Fix trigger command for jenkins job in doc

jenkins/scripts/bml_cleanup.sh, jenkins/scripts/bml_integration_test.sh, jenkins/scripts/fetch_logs.sh
This PR moves running ephemeral cluster from jumphost to internal server in bml. 
1. Jumphost is critical for our lab. Dependencies of project always change and require newer package versions. It creates a risk of breaking OS at any point. OS that we test in CI already newer version than in jumphost. We have already seen package conflicts several times. 
2. After changes Ephemeral cluster (minikube) runs on internal server. We still use jumphost as a proxy to reach internal server.
=> Move ephemeral cluster from jumphost to internal server

prow/config/config.yaml
IPAM release-1.12 check for gomod need to be uplifted to go 1.18, as release-1.2 hack/tools/ is based on go 1.18.
=> prow: uplift go in ipam release-1.2 branch to 1.18

prow/config/config.yaml, prow/config/plugins.yaml
Activate prow for the .github special repository.
=> prow: add metal3-io/.github to prow

jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
ssh-rsa HostKeyAlgorithms is not enabled by default in current ssh version. This PR fixes log collection from virtual serial port of servers in bml
=> Fix serial port log collection in bml

jenkins/scripts/bml_cleanup.sh
In bml_cleanup.sh script deploy-lab ansible playbook called instead of  cleanup-lab playbook. 
This PR fixes this issue.
=> Fix cleaning up ephemeral cluster after successful run in bml

jenkins/README.md, prow/config/config.yaml
e2e triggers format is being unified to format :` /test-<os>-e2e-<type>-<branch>`
related prs:
https://gerrit.nordix.org/c/infra/cicd/+/17454
https://github.com/metal3-io/cluster-api-provider-metal3/pull/883
=> Fix e2e integration trigger naming

prow/config/config.yaml
static-ip-manager-image repo has been archived, and can be removed from prow config.
=> remove static-ip-manager-image from prow

README.md, hack/markdownlint.sh, jenkins/README.md, jenkins/scripts/bare_metal_lab/README.md, prow/README.md, prow/config/config.yaml, prow/ssl/README.md
We have a lot of documentation in this repo, formatted in markdown, but it is not linted. Fix all the issues and add markdownlint linter to keep the files clean.
=> add markdownlint linter and fix markdown issues

prow/config/config.yaml
Add markdownlint and shellcheck for hw-inventory-recorder.
Actual linter scripts being added at: https://github.com/metal3-io/ironic-hardware-inventory-recorder-image/pull/18
=> add basic linters to ihwir

jenkins/scripts/integration_test_env.sh
Removing dictating BMOBRANCH var from project-infra. This was set here to only set main branch periodic tests with main BMO branch and the PR jobs with release tag. But now, we cant afford to do that anymore since main branch BMO is nonbackwards compatible. So dev-env dictates which branch of BMO will be tested. Fixing that in the PR https://github.com/metal3-io/metal3-dev-env/pull/1208
=> Remove BMOBRANCH export

prow/config/config.yaml
Actual linter scripts are added in another PR in ironic-image repo in https://github.com/metal3-io/ironic-image/pull/413
=> add markdownlint for ironic-image

jenkins/README.md, prow/manifests/overlays/metal3/config.yaml
Updates the prow config and README for CAPM3 and IPAM release-1.4 configurations. The ansible required  tests would be replaced with e2e in future.
=> Add release-1.4 branch configurations for CAPM3/IPAM repos

prow/manifests/overlays/metal3/config.yaml
Gradually replacing integration tests with e2e-integration to be the required test. At this step we do that for release-1.4 branch.
=> Add e2e integration as required job for release-1.4 branch

prow/manifests/overlays/metal3/config.yaml, prow/manifests/overlays/metal3/kustomization.yaml
We previously had some components running with older image tags. This synchronizes all container images to use the same tag. All image tags are now set through kustomize to make it easier to find them and update all at once.
This updates the following images (in addition to the util images):
- gcr.io/k8s-prow/label_sync - previous tag: v20211111-bce61c7c4a
- gcr.io/k8s-prow/prow-controller-manager - previous tag: v20211102-f06db4e3d1
- gcr.io/k8s-prow/needs-rebase - previous tag: v20210916-3c87dfedd5
- gcr.io/k8s-prow/cherrypicker - previous tag: v20211111-bce61c7c4a
=> Prow synchronize images

prow/manifests/overlays/metal3/config.yaml
Actual linter scripts are added in another PR in ironic-image repo.
https://github.com/metal3-io/ironic-image/pull/412
=> add shellcheck to ironic-image

prow/infra/ingress-controller-job-patch.yaml, prow/infra/kustomization.yaml
Also added TTL for the Jobs that comes with ingress-nginx. They are supposed to run each time we upgrade, but if the previous job is still there, then we get a naming collision.
=> Prow: Bump ingress-nginx to v1.7.1

jenkins/scripts/files/run_integration_tests.sh
The make target ci_config will skip the different installation in the host during CI run, as those installations are already done during image building.
=> Modify integration test to start with ci_run make target

prow/README.md, prow/capo-cluster/kubeadmcontrolplane.yaml, prow/capo-cluster/machinedeployment.yaml, prow/capo-cluster/openstackmachinetemplates.yaml
- Add documentation for how to upgrade the Kubernetes cluster where Prow is running.
- Add documentation for how to replace or perform maintenance on the bastion host for the Prow cluster.
- Upgrade the Kubernetes cluster to v1.26.4.
=> Prow: Upgrade cluster to v1.26.4 and document

prow/manifests/overlays/metal3/config.yaml
Add markdownlint for ironic-ipa-downloader.
[Another PR](https://github.com/metal3-io/ironic-ipa-downloader/pull/40) will add the actual check in ipa-downloader repo.
=> add markdownlint for ironic-ipa-downloader

jenkins/scripts/integration_test_env.sh
Fixes this: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-4_e2e_integration_test_ubuntu/34/consoleFull
Defaulting CAPM3BRANCH to CAPM3RELEASEBRANCH instead of main. We get CAPM3RELEASEBRANCH variable from jjb, which is different for each release.
=> e2e integeration fix

jenkins/jobs/parallel_e2e_features_test.pipeline
Currently based on consistent test results of the parallel tests, node_reuse doesn't have enough time to fininsh all the test actions before it times out.
=> increase node_reuse timeout to 5 hours in parallel e2e

prow/manifests/overlays/metal3/config.yaml
Update kubeconform linter to v0.6.2.
Each of the repos has separate PR to bump kubeconform for local use as well.
=> update kubeconform to v0.6.2

prow/capo-cluster/kubeadmconfigtemplate.yaml, prow/capo-cluster/kubeadmcontrolplane.yaml, prow/capo-cluster/machinedeployment.yaml, prow/capo-cluster/openstackmachinetemplates.yaml, prow/manifests/overlays/metal3/config.yaml, prow/manifests/overlays/metal3/kustomization.yaml, prow/manifests/overlays/metal3/limitrange.yaml
There are two commits in this PR. The first commit is for upgrading kubernetes to v1.26.6, the second is for reserving resources across the cluster. More details below (from commit messages):
This upgrades the Kubernetes cluster to v1.26.6 and includes a "safety
handle" that was recently added in CAPO templates, namely to set the
provider ID directly through the kubelet. This prevents potential issues
from differences between the OpenStackMachine and server names. If they
differ for some reason, then the cloud controller will not be able to
set the correct provider ID. By telling the kubelet to set the provider
ID directly, we bypass this completely.
This commit adds reserved resources for all nodes. It also sets resource
requests on prow job init containers and sidecar and adds a …
=> Prow: Resources and LimitRanges

prow/README.md
This adds docs for how to temporary scale the workers and how to recover from failed nodes.
There are 2 commits: one just to format the readme (no changes to the content) and one for adding the new sections.
=> Prow: scaling and recovery docs

prow/manifests/overlays/metal3/kustomization.yaml, prow/manifests/overlays/metal3/patches/cherrypicker.yaml, prow/manifests/overlays/metal3/patches/crier.yaml, prow/manifests/overlays/metal3/patches/deck.yaml, prow/manifests/overlays/metal3/patches/ghproxy.yaml, prow/manifests/overlays/metal3/patches/hook.yaml, prow/manifests/overlays/metal3/patches/horologium.yaml, prow/manifests/overlays/metal3/patches/needs-rebase.yaml, prow/manifests/overlays/metal3/patches/prow-controller-manager.yaml, prow/manifests/overlays/metal3/patches/sinker.yaml, prow/manifests/overlays/metal3/patches/statusreconciler.yaml, prow/manifests/overlays/metal3/patches/tide.yaml
This adds resoure requests for CPU and memory for all prow components and external plugins, except the label sync CronJob. We do not currently have data for it, and it is in no way critical.
The requests are based on what I could see in the cluster:
```console
❯ k -n prow top pods
NAME                                       CPU(cores)   MEMORY(bytes)
cherrypicker-6f88fc569d-m2pzb              3m           20Mi
crier-84d95f9cfc-7474n                     34m          54Mi
deck-69dc9f8756-6pmtq                      26m          76Mi
deck-69dc9f8756-ffrwz                      25m          60Mi
ghproxy-79f7d7c4b8-qnd89                   13m          19Mi
hook-65bbf9cdfc-7lgxk                      11m          35Mi
hook-65bbf9cdfc-qpkwh                      15m          36Mi …
```
=> Prow: Resource requests for prow components

prow/manifests/overlays/metal3/config.yaml
ipa-downloader is an init container, which is k8s concept. On Ubuntu integration, it is manually executed (using wrong image, currently), so it is not actually testing it properly. Centos one is running the init container as it should be running, so making it the mandatory test for ipa-downloader repo.
=> change the ipa-downloader required test to centos

prow/manifests/overlays/metal3/config.yaml
Golint and gofmt were configured to only run then .go files were changed, but these jobs could also be affected by changes to go.mod and other files (e.g. version changes).
=> Run golint and gofmt on more changes in BMO

prow/manifests/overlays/metal3/config.yaml
Currently this job only builds if `api/` or `test/` or `Makefile` change, but `make build` also builds the main binary from top-level. It might be confusing to users to see this job pass/fail differently from other jobs that build top-level as well, so triggering the build job here as well.
=> build capm3 if almost any file changes

prow/manifests/overlays/metal3/config.yaml
This PR also drops golangci-lint prow test for CAPM3 main branch since it would be run through github workflow from now on.
=> Bump golang to v1.20 for CAPM3 main branch prow tests

jenkins/scripts/files/run_fetch_logs.sh
Before_pivoting folder will only be created if there is a snapshot to put into it. After_pivoting folder renamed to final_logs.
=> Fixes confusing log placements on failing runs.

jenkins/jobs/integration_tests.pipeline
=> Fix 6hr timeout on e2e integration tests

prow/manifests/overlays/metal3/config.yaml
This PR drops golangci-lint prow test for IPAM main branch since it would be run through github workflow from now on once https://github.com/metal3-io/ip-address-manager/pull/284 lands.
=> Remove golangci-lint prow test for IPAM main branch

jenkins/scripts/integration_test_env.sh
In fact the download was never disabled, dev-env is downloading IPA based on a different logic. Exporting the IPA_DOWNLOAD_ENABLED=false variable is not needed until there is an established process of pinning the IPA version for CI test jobs.
This variable is also blocking  https://github.com/metal3-io/metal3-dev-env/pull/1272 .
=> re-enable IPA download in tests

jenkins/scripts/files/run_integration_tests.sh
we need to test 01_  script also for dev-env PRs which is currently skipped since we use ci_run make target. This PR correct  for the dev-env PRs to use make command which includes the script.
=> Fix make target for dev-env PRs

jenkins/scripts/fetch_logs.sh, jenkins/scripts/integration_clean.sh, jenkins/scripts/integration_delete.sh, jenkins/scripts/integration_test.sh, jenkins/scripts/integration_test_clean.sh, jenkins/scripts/ironic_image_build_test_delete.sh
This PR spreads tests across regions and projects as following:
- e2e features, clusterclt-upgrade tests in Frankfurt region
- ansible, e2e, basic integration, k8s-upgrade tests in Karlskrona region
- keep tests in dev2 project Karlskrona region
=> Spread tests across projects and regions in cloud

jenkins/README.md, prow/manifests/overlays/metal3/config.yaml
This updates the prow config to include the release-1.5 branch for CAPM3 and IPAM. The "required status checks" are also updated to include the new branches and drop older requirements.
=> Add release-1.5 branch configurations

prow/manifests/base/ghproxy.yaml
We are not running a pushgateway so there is no point trying to push any metrics to it. This was causing lots of error messages in the ghproxy logs.
=> Prow: Disable ghproxy pushgateway

jenkins/scripts/fetch_logs.sh
This commit:
- Adds a default value to the KEEP_TEST_ENV variable that is used during log fetching. The missing default value was causing "unbound variable" error.
=> add missing default value to KEEP_TEST_ENV

jenkins/scripts/fetch_logs.sh, jenkins/scripts/integration_delete.sh
This PR fixes unbound variables issue, when running dev-tools-integration-tests.
=> Fix unbound variables for dev tools integration tests

jenkins/scripts/integration_test.sh
This PR sets `8C-24GB-300GB` flavor for pivoting, remediation, k8s-upgrade features tests VMs and keeps `8C-32GB-300GB` flavor for Clusterctl-upgrade test, since it uses 5 nodes.
=> Change flavor for e2e feature test host vms

prow/manifests/overlays/metal3/config.yaml
Gosec is part of golangci-lint, so remove Prow for it.
Instead, we're not testing "make test" or changes to hack/* files in CI, so add "make test" prow job.
=> remove gosec from main, add make test, for IPAM

prow/manifests/overlays/metal3/config.yaml
Gosec is run part of golangci-lint, so it can be removed from main. Instead, we need to test Makefile and hack/.* file changes somewhere, hence we add "test" job for main, which runs "make test" which runs unit, linter etc, verifying most of our hack scripts and Makefile.
=> remove capm3 gosec and add make test

prow/manifests/overlays/metal3/config.yaml
Remove gosec from IPAM/CAPM3 release-1.5 branches, but add "make test" instead to match main.
Requires: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1218 and https://github.com/metal3-io/ip-address-manager/pull/329 to be merged first.
/hold
=> remove gosec, add test to capm3/ipam release-1.5

prow/manifests/overlays/metal3/config.yaml
This commit:
- Adds tide support for the metal3-io/utility-images repo
- Adds shellcheck and markdownlint support for the metal3-io/utility-images repo
=> add prow support for utility-images

jenkins/scripts/integration_test.sh
This PR:
- Increases the ServerAliveInterval  of any job that uses the integration_test.sh
script from 2.5 min to 20 min. This change aims to make the ssh connection more
patient at times when the test workloads are not generating any ssh traffic.
=> increase ssh inactivity tolerance in test jobs 

prow/Makefile, prow/manifests/overlays/metal3/config.yaml, prow/manifests/overlays/metal3/kustomization.yaml
This PR will add the latest images for prow containers and different components with latest tag `v20231011-33fbc60185`. This latest tag will synchronize all container images to use the same tag. All image tags are now set through kustomize to make it easier to identify and update all at once. Also Make target file had older tag `v20210916-3c87dfedd5` which is also changed to latest.
This updates the following images (in addition to the util images):
```
config.yaml
gcr.io/k8s-prow/label_sync - previous tag: v20230329-c93d79fb7d
gcr.io/k8s-prow/prow-controller-manager - previous tag: v20230329-c93d79fb7d
gcr.io/k8s-prow/needs-rebase - previous tag: v20230329-c93d79fb7d
gcr.io/k8s-prow/cherrypicker - previous tag: v20230329-c93d79fb7d
```
=> Uplift prow container images

prow/manifests/overlays/metal3/config.yaml
These image had older image tag and needed to uplift to the latest tag v20231011-33fbc60185. It has older image tag:
```
gcr.io/k8s-prow/commenter:v20210916-3c87dfedd5
gcr.io/k8s-prow/commenter:v20210916-3c87dfedd5
gcr.io/k8s-prow/checkconfig:v20210916-7657ce97bf
```
=> Add latest image tag in configuration

prow/manifests/overlays/metal3/config.yaml
We have prow jobs that fail with
```
{"component":"entrypoint","error":"could not start the process: fork/exec /app/robots/commenter/app.binary: no such file or directory","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-10-24T17:46:51Z"}
```
There was a change in upstream that we missed when bumping the image tags.
See https://github.com/kubernetes/test-infra/pull/25384/files
=> Prow: Fix commenter and checkconfig command

prow/infra/add-args.yaml, prow/infra/configmap-patch.yaml, prow/infra/kustomization.yaml
This bumps the ingress-nginx version and enables mitigations for 3 CVEs.
- https://github.com/advisories/GHSA-5wj4-wffq-3378
- https://github.com/advisories/GHSA-gvrm-w2f9-f77q
- https://github.com/advisories/GHSA-fp9f-44c2-cw27
The CVEs are all rated High, but require that the attacker has access to the Kubernetes cluster and is able to create or modify annotations on the ingress resources.
Note: Future versions of ingress-nginx may enable these mitigations by default, at which point we can remove these extra patches.
The changes has been applied in the cluster. :heavy_check_mark:
=> Prow: Update ingress-nginx to v1.9.4

jenkins/scripts/bare_metal_lab/tasks/cleanup-tasks.yaml
We already prune containers, images and volumes, but docker was still taking up more than 60 GB. It was all cleaned up with docker system prune.
=> BML: prune docker storage

prow/manifests/overlays/metal3/config.yaml, prow/manifests/overlays/metal3/plugins.yaml
This commit:
- sets up prow based static analysis tests for the Nordix/sles-ironic-python-agent-builder repository
=> add prow support for sles-ironic-python-agent-builder

prow/manifests/overlays/metal3/config.yaml
When bumping markdownlint I noticed the linter change isn't actually tested in Prow as no .md files were changed.
Run markdownlint when touching the linter script, so the rule ignores as well as component bumps get tested.
=> run markdownlint when changing the linter

prow/manifests/overlays/metal3/config.yaml, prow/manifests/overlays/metal3/plugins.yaml
This PR also adds a markdownlint prow job for the repo.
=> Add metal3-io/community repository in prow config

prow/manifests/overlays/metal3/config.yaml
Bump markdownlint for all repos to 0.13.0.
/hold
until all the bump PRs in the repos have been merged, so this bump won't cause Prow failures in unrelated PRs.
=> bump markdownlint to 0.13.0

prow/manifests/overlays/metal3/config.yaml
Bump gosec to 2.18.2 for BMO.
Do not bump CAPM3/IPAM gosec as it is used in release-1.3 and 1.4, but release-1.3 is no longer maintained, and hence we'd need to fork the project-infra config between the two. 1.4 is also going to be moved out of support soon when 1.6 releases.
/hold
Needs:
https://github.com/metal3-io/baremetal-operator/pull/1476, https://github.com/metal3-io/baremetal-operator/pull/1475, https://github.com/metal3-io/baremetal-operator/pull/1474 to merge first.
=> bump gosec to 2.18.2

prow/.gitignore, prow/README.md, prow/manifests/overlays/metal3/config.yaml, prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml, prow/manifests/overlays/metal3/kustomization.yaml, prow/manifests/overlays/metal3/patches/jenkins-operator.yaml
The name is a bit misleading unfortunately. This prow component is used to trigger jenkins jobs. It will allow us to have one common way to trigger all tests (except github workflows) and we can stop using the ghprb jenkins plugin that is no longer maintained.
=> Add jenkins-operator for prow

jenkins/jobs/bmo_e2e_tests.pipeline
This is needed before we can add a matrix to the pipeline. Otherwise the parallel tests would overwrite each others artifacts...
=> BMO e2e: Allow flexible artifact naming

jenkins/jobs/bmo_e2e_tests.pipeline
This adds a matrix to the BMO e2e pipeline so that both VBMC and sushy-tools can be tested in parallel.
TODO:
=> BMO e2e pipeline matrix

jenkins/README.md, prow/manifests/overlays/metal3/config.yaml
Adding release-1.6 branch configurations for CAPM3/IPAM repos
=> Add release-1.6 branch configurations for CAPM3/IPAM repos

prow/manifests/overlays/metal3/config.yaml
I propose we make the e2e tests required for BMO now. They exist on main and release-0.5 so this is what I added.
We could also remove one or both CAPM3 based jobs, but perhaps better to do that separately?
=> Make BMO e2e tests required status check

jenkins/jobs/bml_integration_tests.pipeline, jenkins/jobs/bmo_e2e_tests.pipeline, jenkins/jobs/integration_tests.pipeline, jenkins/jobs/integration_tests_clean.pipeline, jenkins/jobs/ironic_image_build_test.pipeline, jenkins/jobs/parallel_e2e_features_test.pipeline
This commit enables build log timestamps in all pipeline scripts with a 1 second resolution.
=> enable build timestamps

jenkins/jobs/parallel_e2e_features_test.pipeline, jenkins/scripts/dynamic_worker_workflow/feature_tests.sh, jenkins/scripts/dynamic_worker_workflow/fetch_logs.sh, jenkins/scripts/dynamic_worker_workflow/integration_test_env.sh, jenkins/scripts/dynamic_worker_workflow/run_clean.sh
This PR makes feature tests run directly in dynamic workers instead of using worker as a jumphost
=> Run feature tests in dynamic Jenkins workers

jenkins/README.md, prow/manifests/overlays/metal3/config.yaml
We no longer run release-1.3 tests in Prow. We run tests for 1.4, and support 1.5, 1.6 and main.
=> remove release-1.3 from prow

jenkins/jobs/bmo_e2e_tests.pipeline
This change is needed for the new jenkins job, which runs BMO E2E upgrade tests.
Related jjb changes: https://gerrit.nordix.org/c/infra/cicd/+/20387
=> Add BMO upgrade tests pipeline

jenkins/jobs/bmo_e2e_tests.pipeline, prow/manifests/overlays/metal3/config.yaml
This is to verify that the jenkins operator for prow works as expected. The idea is to trigger jenkins jobs through prow instead of through the ghprb jenkins plugin. When we have verified that this works, we can continue with the rest of the jenkins jobs and remove the ghprb triggers.
=> Trigger BMO e2e tests through prow

prow/manifests/overlays/metal3/config.yaml
I think this is the reason we do not get links to the jenkins build and logs.
API ref: https://github.com/kubernetes/test-infra/blob/8a9df5c914af259a641c9362aca124d9238960e6/prow/apis/prowjobs/v1/types.go#L1069
Error seen in the logs:
```
{"component":"jenkins-operator","event-GUID":"f78845c0-b5e7-11ee-9678-d4a6c200b850","file":"k8s.io/test-infra/prow/jenkins/controller.go:395","func":"k8s.io/test-infra/prow/jenkins.(*Controller).syncPendingJob","job":"metal3-bmo-e2e-test-pull","level":"error","msg":"error executing URL template: template: JobURL:1:66: executing \"JobURL\" at \u003c.Status.JenkinsBuildId\u003e: can't evaluate field JenkinsBuildId in type v1.ProwJobStatus","name":"6ce9f938-39b2-44ab-98eb-ec6c591b8044","org":"metal3-io","pr":1520,"repo":"baremetal-operator","severity":"error …
```
=> Fix typos in prow config for jenkins-operator

prow/manifests/overlays/metal3/config.yaml
This removes the required status context for BMO e2e tests and instead makes the prow job required.
It also removes the report template because this is already covered by the report template set for plank. This config is currently causing double messages when a job fails (one for jenkins and one for plank).
One thing to discuss, test and decide is how to handle these required jobs.
Other required jobs that we have run automatically when needed. The e2e jobs have traditionally been manually triggered only to save some resources. I'm not sure if a required but not automatically run job will show up in the status contexts. If not, we have to decide if we
1. Add required status contexts back for them, or
2. Run the jobs automatically. If we choose this we can also use config like "skip if …
=> Make BMO e2e prow job required

jenkins/jobs/bmo_e2e_tests.pipeline
We are no longer using the ghprb plugin to trigger these tests so the variable can now be removed completely.
=> Remove the ghprb variable from BMO e2e pipeline

.markdownlint-cli2.yaml, hack/markdownlint.sh, prow/README.md, prow/manifests/overlays/metal3/config.yaml
Switch markdownlint container to markdownlint-cli2. This CLI version supports the enable/disable rules in markdown files and allows us to ignore issues locally, not just globally.
TODO: 
1. we need to get each of the reviews pointing at this to be approved, lgtm'd and held; the larger the batch the better
2. we need to merge this in one more multiple pieces (more likely)
=> switch markdownlint container to markdownlint-cli2

prow/manifests/overlays/metal3/config.yaml
We earlier removed yaspeller that worked via pre-commit hook. This replaces the spellchecking using basically the same dictionary, but using node/npx cspell to do the spell checking.
Actual spellcheck script is done in PR
https://github.com/metal3-io/metal3-io.github.io/pull/391
This should be merged first, so we can test the check in the target repo.
=> add spellchecker prow test for website repo

prow/manifests/overlays/metal3/config.yaml
Add spellchecker for documentation.
Add shellcheck to lint the hack scripts.
Linters added in https://github.com/metal3-io/metal3-docs/pull/379
/hold
Until both have flags.
=> add spellcheck and shellcheck for metal3-docs

prow/manifests/overlays/metal3/config.yaml
The BMO e2e tests have now been required for PRs in BMO for a couple of weeks already. They test more extensively and efficiently than the old integration test so I suggest we make it optional.
=> Update required contexts for BMO

prow/infra/kustomization.yaml
Just keeping up with the upstream. Nothing newsworthy in the changelog.
=> Prow: Bump ingress-nginx to v1.9.6

prow/manifests/overlays/metal3/config.yaml
=> Bump golang to v1.21 for BMO prow jobs

prow/manifests/overlays/metal3/kustomization.yaml
The patches used to add resource requests for all prow containers were mistakenly removed when adding the autobumper. This commits restores them.
(The files that they refer to are still there.)
=> Prow: Restore patches that were mistakenly removed

jenkins/scripts/integration_test.sh
This is temporarily disabled to see if we can get the tests green.
=> Disable health check for CI VMs

jenkins/scripts/files/run_integration_tests.sh
Skipping 01 scripts has caused quite a few issues lately. Lets run it in all ansible integration tests to avoid confusion.
=> Run dev-env's 01 scripts in all integration tests

jenkins/jobs/prow_integration_tests.pipeline
This supposed to be the full link but in the environment vlock it was initiated to only repo name this PR fix that and reorder the vars
=> Fix UPDATED_REPO in the pipeline for e2e test trigger from prow

jenkins/jobs/bmo_e2e_tests.pipeline
Git won't merge without the user details.
```
ERROR: Branch not suitable for integration as it does not merge cleanly: Command "git merge --ff 1c35b0222619831faee2d624f9c60685479a561c" returned status code 128:
stdout: 
stderr: Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'metal3ci@metal3-worker-591.(none)')
```
Relevant docs for scmGit: https://www.jenkins.io/doc/pipeline/steps/params/scmgit/
=> BMO e2e: Set user name and email for git

prow/manifests/overlays/metal3/config.yaml
Weekly is a bit much so this changes the schedule to monthly.
=> Prow: Run autobumper monthly

jenkins/jobs/prow_integration_tests.pipeline, prow/manifests/overlays/metal3/config.yaml
this PR fix the branch issue when triggering basic e2e from prow and make it also runnable on project infra
=> 🌱 Run prow triggerable basic e2e on project-infra and fix branch issue

prow/manifests/overlays/metal3/config.yaml
Add prow trigger for basic e2e test from project-infra, dev-env, bmo and ipam for ubuntu and centos following the jjb name format here https://gerrit.nordix.org/c/infra/cicd/+/20718
=> Make basic e2e test triggerable from different repos and os

jenkins/scripts/integration_test.sh, jenkins/scripts/utils.sh
The output can contain text that matches even though no fatal error occurred. Since we no longer have the issue where centos is always failing cloud-init, we can now actually check the exit code.
=> Check CI VM cloud-init exit code instead of output

prow/manifests/overlays/metal3/config.yaml
seems that names that include "." will not work
=> Fix prow trigger naming for basic e2e test

jenkins/jobs/bml_integration_tests.pipeline, jenkins/scripts/bml_cleanup.sh, jenkins/scripts/bml_integration_test.sh, jenkins/scripts/fetch_logs.sh
This PR:
- sets new jenkins worker (vm inside a Jumphost) to be used for bml jobs 
- removes Jumphost related logic from bml scripts
- changes jenkins agent label for bml jobs
=> Set jenkins worker for BML job

jenkins/jobs/capm3-e2e-tests.pipeline
changing `SecureRandom()` to `Random()`, because it fails with following error.
`Scripts not permitted to use new java.security.SecureRandom. Administrators can decide whether to approve or reject this signature.`
=> Minor fix in e2e pipeline script.

jenkins/jobs/dev_env_integration_tests.pipeline, jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Switching static workers to dynamic workers for integration tests. Also separating metal3 dev env and upgrade integration tests to keep code more maintainable.
=> :sparkles:  Switch integration tests from static workers to dynamic workers

jenkins/image_building/dib_elements/ubuntu-ci/post-install.d/configure
in centos images we use dns servers that are provided by openstack network, This PR makes ubuntu ci images to use dns provided dns names
=> Use dhcp provided dns address for metal3ci ubuntu images

jenkins/scripts/dynamic_worker_workflow/feature_tests.sh, jenkins/scripts/files/run_integration_tests.sh
Prow jenkins operator does not propagate vars to the sources branch of the PR so we have to pull changes form the PR id
=> Fetch changes from PR id with prow feature tests triggers

prow/manifests/overlays/metal3/config.yaml, prow/manifests/overlays/metal3/plugins.yaml
This commit:
- Adds markdownlint and go mod tests for ironic-standalone-operator
- Adds basic prow branch protection for ironic-standalone-operator
=> Initialize prow support for ironic-standalone-operator

prow/README.md, prow/capo-cluster/machinedeployment.yaml, prow/cluster-resources/autoscaler.yaml, prow/cluster-resources/coredns-pdb.yaml, prow/cluster-resources/kustomization.yaml
This adds the cluster-autoscaler to the prow cluster and configures the MachineDeployment to be managed by it. It is configured to scale between 1 and 5 replicas.
The deployment manifest is based on the upstream example. The autoscaler is configured to run on control-plane nodes only, as recommended by upstream. It has the necessary RBAC to manage resources in the prow cluster itself but nothing else.
=> Add cluster-autoscaler for prow cluster

prow/capo-cluster/infra-kct.yaml, prow/capo-cluster/infra-md.yaml, prow/capo-cluster/kustomization.yaml, prow/cluster-resources/kustomization.yaml, prow/cluster-resources/toleration-node-selector-patch.yaml, prow/infra/kustomization.yaml, prow/infra/toleration-node-selector-patch.yaml, prow/manifests/overlays/metal3/kustomization.yaml, prow/manifests/overlays/metal3/toleration-node-selector-patch.yaml
This adds a separate node pool for everything that isn't a prow job or
running on the control-plane. The node pool has a taint to prevent
workload running there by accident. All relevant workload now has
toleration for this taint and a node selector to always run in this node
pool.
=> Prow: Add infra node pool

jenkins/jobs/capm3-e2e-tests.pipeline, jenkins/jobs/parallel_e2e_features_test.pipeline, jenkins/jobs/prow_integration_tests.pipeline
It seems when we trigger a test from prow on project infra branch it fails because it cannot fetch the PR branch ! e.g https://jenkins.nordix.org/view/Metal3/job/metal3-e2e-clusterctl-upgrade-test-main/5/
This PR might help with this issue
=> Fix refspec with prow pipeline when running on project-infra PRs

jenkins/jobs/bmo_e2e_tests.pipeline
We can now set the BMC protocol directly instead of specifying the emulator and optionally the sushy-tools protocol.
=> Simplify BMO e2e pipeline matrix

prow/manifests/overlays/metal3/config.yaml
Update ironic-image required tests to Prow tests. Remove optional tests as they conflict with required tests, and make little sense to be available cross-releases.
=> update ironic-image required tests to Prow tests

jenkins/jobs/capm3-e2e-tests.pipeline
clusterctl upgrade tests are aborting because of timeout:
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-e2e-clusterctl-upgrade-test-main/5/
This PR is increasing the timeout.
=> 🌱 Increasing timout for clusterctl upgrade tests

jenkins/README.md, prow/manifests/overlays/metal3/config.yaml
Updating prow config to accommodate CAPM3 and IPAM release-1.7 and BMO release-0.6.0
=> 🌱  Update for CAPM3 and IPAM release-1.7 and BMO 0.6.0

prow/manifests/overlays/metal3/config.yaml
Switch the required prow tests to be consistent with what we want to have without Jenkins GHPRB tests being present.
Changes summarized:
- remove all Jenkins GHPRB required contexts (except dev-tools), kept `protect: true`
- project-infra only ubuntu main
- dev-env is centos 1.7, ubuntu main
- CAPM3/IPAM in main is main+main, release branches only centos, remove ubuntu
- ironic-image release 1.7 to 24.1 as it should be
- BMO release branches have 1.7/1.6/1.5 correspondingly
- removed stray/empty branches from ipa-downloader (it doesn't have branches)
=> revise required Prow tests

prow/capo-cluster/cluster.yaml, prow/capo-cluster/infra-md.yaml, prow/capo-cluster/kubeadmcontrolplane.yaml, prow/capo-cluster/machinedeployment.yaml, prow/capo-cluster/openstackcluster.yaml, prow/capo-cluster/openstackmachinetemplates.yaml
The latest release of CAPO came with a new API version. This commit updates all manifests to use that version. This is essentially a no-op in the cluster as all resources are anyway converted back and forth automatically by the webhook as needed.
The biggest change are the managed security groups. They used to be hard-coded in CAPO to match what is needed for Calico. Now they must be specified explicitly.
=> Prow: Update CAPO resources to use v1beta1 API

jenkins/jobs/dev_env_integration_tests.pipeline, jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh, jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh, jenkins/scripts/dynamic_worker_workflow/fetch_logs.sh, jenkins/scripts/dynamic_worker_workflow/run_clean.sh, jenkins/scripts/dynamic_worker_workflow/test_env.sh
Dev tests are failing with UPDATED_REPO unbound variable issue. It was initially defined and was not passed to test env. This PR fixes this issue. 
Also specifies full path for cloning repos.
=> Fix unbound var and specify repo dir in full path

hack/prow_test_dumper.py
Add prow_test_dumper.py to hack/. It will read the prow config.yaml and spit out branch protection settings it finds. Supports "branch-protection" and "presubmits" sections. Does not support split prow config, so reads only one file at a time.
Requires python3 and pyyaml (`pip3 install pyyaml`). Use virtualenv's responsibly.
Example output: https://github.com/metal3-io/project-infra/pull/714#issuecomment-2078910887 
Script location and naming suggestion welcome.
=> add prow test config dumper

jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
This PR defines KUBERNETES_VERSION, FROM_K8S_VERSION and KUBECTL_SHA256  varibles for k8s upgrade tests.
(I forgot to add this when I moved  k8s upgrade tests to dynamic worker workflow)
=> Define KUBERNETES_VERSION and  related variables for k8s upgrade tests

prow/manifests/overlays/metal3/config.yaml
The BMO e2e tests have proven themselves over several months now. They are on par with the CAPM3 tests regarding the BMO features they test and they do it faster and more efficiently. By requiring both CAPM3 and BMO e2e tests to run on all BMO PRs we make the PR process unnessarily heavy, time consuming and resource intense.
This commit is for making the last remaining CAPM3 e2e test optional on BMO PRs. Note that CAPM3 tests can still be triggered if wanted, they will just not be required. They are also still running as daily jobs so we will quickly notice if something breaks.
I think `metal3-ubuntu-e2e-integration-test-main` was mistakenly set to required when switching to prow triggered jobs. This has not been required in BMO before.
=> BMO: Make CAPM3 e2e tests optional

prow/manifests/overlays/metal3/plugins.yaml
Blunderbuss is a Prow plugin that selects and asks reviewers to review PRs. Unfortunately the docs are a bit on the light side for how to actually configure it. The available docs can be found here: https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#blunderbuss-and-reviewers
I have used the test-infra configuration as example to learn how to actually configure it.
https://github.com/kubernetes/test-infra/blob/75d0608061cac39e624fad37b4f082dfa84e7ba5/config/prow/plugins.yaml#L331-L333
The configuration in this commit should select 2 reviewers for each PR for all metal3.io PRs and respect the GitHub status. (If you set yourself as busy it won't pick you.)
=> Prow: Enable blunderbuss

jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
This fixes the issue of running e2e integration tests from wrong repo for metal3-dev-env PR tests. 
Example here: https://jenkins.nordix.org/view/Metal3/job/metal3-centos-e2e-integration-test-release-1-7/20/console
=> Fix e2e integration test run from metal3-dev-env repo PR

jenkins/jobs/bmo_e2e_tests.pipeline
We are trying to reduce Cleura usage and move jobs to Xerces. BMO e2e tests are a good first candidate.
=> Move BMO e2e jobs to run on Xerces workers

prow/manifests/overlays/metal3/config.yaml
BMO e2e was agreed to be good enough. For some reason, integration e2e centos was left on in 0.6 branch, but correctly removed from main and 0.5.
=> remove e2e from bmo 0.6 branch as required

jenkins/jobs/bmo_e2e_tests.pipeline
We are seeing some optional jobs hit the 1 h timeout. This commit increases the timeout to 2 h.
=> Increase BMO e2e timeout

jenkins/jobs/capm3-e2e-tests.pipeline, jenkins/jobs/dev_env_integration_tests.pipeline
This PR:
- sets timeout for integration tests to 3 hours (Due to ongoing CI infrastructure changes)
- sets timeout to 5h for Ephemeral tests
=> Adjust timeout for tests

prow/manifests/overlays/metal3/config.yaml
metal3-dev-env tests should be required for PR in metal3-dev-env repo.
=> Set dev env tests as required for metal3-dev-env repo

jenkins/jobs/bml_integration_tests.pipeline, jenkins/jobs/bmo_e2e_tests.pipeline, jenkins/jobs/capm3-e2e-tests.pipeline, jenkins/jobs/dev_env_integration_tests.pipeline, jenkins/jobs/image_building.pipeline, jenkins/jobs/integration_tests.pipeline, jenkins/jobs/integration_tests_clean.pipeline, jenkins/jobs/parallel_e2e_features_test.pipeline, jenkins/jobs/prow_integration_tests.pipeline
We have been using the wrong credentials ID, resulting in "not found" errors (but still working without credentials). The thing is that the git plugin only supports username/password, NOT token. We have been trying to use a token for checking out the tested repo. We have been using the correct credentials for checking out project-infra though.
This PR changes all pipelines to use the same credentials ID we always used for checking out project-infra.
=> Fix git credentials ID

prow/manifests/overlays/metal3/config.yaml
Now that we trigger jenkins jobs through Prow, we have some jobs that can take more than 4h. Increasing to 24h.
Edit: I suspect this may be why we have seen some jobs fail but report success (https://github.com/kubernetes-sigs/prow/issues/142). If the prowjob was cleaned up, then what would the jenkins-operator do? :thinking:
=> Prow: Increase max prowjob age to 24h

prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml
We currently see double comments on github when jenkins jobs fail. I think the issue is that the jenkins-operator reports the failure once and prow itself reports it a second time (since the job also has a corresponding prowjob). If this is accurate, we can solve the issue by disabling reports from the jenkins-operator, which is what this commit does.
=> Prow: Skip job report from jenkins-operator

prow/manifests/overlays/metal3/plugins.yaml
This should allow Prow to trigger (and re-trigger) workflows, making it possible for non-admins to re-run failed workflows.
=> Prow: Enable triggering of GitHub workflows

jenkins/jobs/capm3-e2e-tests.pipeline
e2e tests fail with the following error:
```
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: e674ac0b-023f-4ef1-bb05-8ae6135101ec
groovy.lang.MissingPropertyException: No such property: EPHEMERAL_TEST for class: groovy.lang.Binding
```
ref: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-e2e-1-28-1-29-upgrade-main/32/console 
This PR is fixing it.
=> 🐛 Fixing EPHEMERAL_TEST variable

prow/manifests/overlays/metal3/plugins.yaml
This should hopefully make it possible to retrigger GitHub workflows on all repos in metal3-io.
=> Prow: Add metal3-io org to triggers config

prow/manifests/overlays/metal3/config.yaml
Add support for skipping tests if OWNERS_ALIASES is modified, same as OWNERS before it. I will do another PR where I add more skips to tests, this one only modifies existing skips.
This is required for supporting owner aliases which is needed to fix blunderbuss review requests.
=> skip if only OWNERS_ALIASES is modified

jenkins/image_building/authorized_keys, jenkins/image_building/build-image.sh
This is part of rotating keys we will eventually remove the old key once we have verified everything works with the new key.
The new key details are available in the password manager. 
Fixes: #765
=> Add new key to authorized_keys in the DiB build

prow/manifests/overlays/metal3/plugins.yaml
It has two branches, enable cherrypicker for it.
=> add cherrypicker to sles-ironic-python-agent-builder

prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml
Disabling the reporting did get rid of the double failure messages, but it also broke updates to the status contexts. They only updated after jobs completed or not at all.
Therefore we enable reporting again.
=> Prow: Enable reporting again in jenkins-operator

jenkins/image_building/build-image.sh
Centos image building is broken with wrong partition UUID error. Here is the[ fix in the upstream](https://github.com/openstack/diskimage-builder/commit/c03e46d9e1244d6ee2ac85ff119fed54b7e08c0e). 
Until diskimage-builder is released, we need to built it from fix commit in master branch.
=> Build diskimage builder from upstream commit until next release

prow/manifests/overlays/metal3/config.yaml
This PR bumps main branch golang version to go v1.22 for CAPM3, BMO and IPAM prow jobs. Only remaining repo in this config file is metal3-io/ironic-standalone-operator whic will still be using go 1.21 in main branch prow tests. We need to tackle that in a separate PR once a consensus is reached for that repo.
=> Bump golang to v1.22 for CAPM3, BMO and IPAM prow jobs

prow/manifests/overlays/metal3/config.yaml
We are moving the GitHub workflows so we should no longer require the jenkins job. Still leaving it as optional though so we can trigger it if wanted.
=> Make BMO e2e tests optional

prow/manifests/overlays/metal3/config.yaml
Bump Go image to 1.22 for ironic-standalone-operator tests, as we're bumping Go to 1.22 there.
=> bump go 1.22 for ironic-standalone-operator

prow/manifests/base/hook.yaml
This PR will remove the loadbalancer and revert back to DNS hook.
=> Prow cleanup and use DNS hook.

prow/manifests/overlays/metal3/config.yaml
Bml integration tests were missing in prow config. 
This PR adds bml integration tests jobs for metal3-dev-env and project infra repos.
=> Add bml integration tests jobs to prow

jenkins/image_building/build-image.sh, jenkins/image_building/verify-node-image.sh, jenkins/scripts/dynamic_worker_workflow/test_env.sh
With this change, build node images will be verified with integration tests before they are pushed online.
=> Add image testing to node image building process

prow/container-images/basic-checks/Dockerfile, prow/container-images/basic-checks/README.md
In prow we are currently using `docker.io/golang` as the container image to run various basic tests: `generate`, `gomod`, lint, etc. It has worked well so far, but will fail the tests if something extra is required from the container environment, as in the case of https://github.com/metal3-io/baremetal-operator/pull/1767, which requires libvirt.
This PR adds a new Dockerfile that will be used to build a new container image, that takes `docker.io/golang` as base. For now we configure it so that a new container image will be pushed once a new tag is pushed to the github repository.
=> :seedling: Add config for basic-checks container image

prow/manifests/overlays/metal3/config.yaml
As mentioned by https://github.com/metal3-io/project-infra/pull/796, this PR is to replace `docker.io/golang` with `quay.io/metal3-io/basic-checks` image
=> :seedling: Use basic-checks image instead of docker.io/golang for basic tests in BMO repo

prow/manifests/overlays/metal3/config.yaml
Bump spellcheck container from 8.3.2 to 8.9.0.
Docs and Website repos have their own bump PRs. No other changes are required, so order of merging doesn't matter.
=> bump spellcheck to 8.9.0

prow/container-images/basic-checks/Dockerfile
Make basic-checks image a bit smaller by running apt-get clean after package installation.
=> cleanup basic-checks image

jenkins/image_building/build-image.sh, jenkins/image_building/upload-ci-image.sh
https://github.com/metal3-io/project-infra/pull/784/ changed the default image format to be created to raw. But this also effect node image building and we still want qcow2 to be the format for that. This PR changes this behavior to build qcow2 images by default. This PR also ensures we delete the images once uploaded to openstack from dynamic worker vms.
=> Build qcow2 image instead of raw by default

jenkins/image_building/authorized_keys
This is part of the CI key rotation. The new key seems to work in most of the CI jobs. This PR gets rid of the old one.
=> Remove old SSH key from the CI image

jenkins/scripts/dynamic_worker_workflow/bmh-patch-short-serial.yaml, jenkins/scripts/dynamic_worker_workflow/build_ipa.sh
This commit:
- Adds missing bmo serial patch for the fullstack test workflow.
=> add missing bmo serial patch for fullstack test

jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Cleanup the test repo location (`$HOME/tested_repo`) before cloning. To avoid the issue we face in CI: https://jenkins.nordix.org/job/metal3_periodic_node_image_building/34/consoleFull
```
+ /home/****/workspace/metal3_periodic_node_image_building/jenkins/image_building/../scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
fatal: destination path '/home/****/tested_repo' already exists and is not an empty directory.
```
=> :seedling: Make sure the git clone destination is empty

jenkins/image_building/build-image.sh, jenkins/image_building/verify-node-image.sh
[node_image_building](https://jenkins.nordix.org/job/metal3_periodic_node_image_building/) is currently failing because the location of the file is incorrect. The built image locates in the directory, from where the script is run (which is the repo root), while the verify script assumes that image locates in `jenkins/image_building`.
This PR fixes the IMAGE_LOCATION, so that dev-env could find the image.
Edit: Also add the `${IMAGE_NAME}.d` directory cleanup. This directory was created as a part of the image building.
=> :bug: Fix IMAGE_LOCATION in build-image.sh

prow/manifests/overlays/metal3/config.yaml
Removing CAPM3 release-1.5 clusterctl tests, we removing support for CAPM3 release-1.5 in a month.
=> 🌱 Remove 1.5 clusterctl tests

jenkins/jobs/image_building.pipeline
Because we run the `dev-env` test to verify the images after building them, 40 minutes isn't long enough.
=> :bug: Increase timeout minutes for node image building pipeline

jenkins/image_building/verify-node-image.sh, jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Add an option to cleanup the system (by running dev-env `make clean`) after integration test. This is to make sure the next pipeline can start from a clean state, hence avoid issues like the one we see in https://jenkins.nordix.org/job/metal3_periodic_node_image_building/38/
=> :seedling: Set trap to run `make clean` after integration test

prow/manifests/overlays/metal3/config.yaml
Go 1.21 is deprecating in August and 1.7 release is still supported in capm3 so bump the go version in testing to be able to get the capm3 PR in. 
It will say this is needed for the following PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1852
=> Update prow config to test release 1.7 of capm3 with go v1.22

prow/manifests/overlays/metal3/config.yaml
Since golang 1.21 is deprecating in August 2024
Needed for this PR in BMO: https://github.com/metal3-io/baremetal-operator/pull/1824
=> Test bmo release 0.6 with golang 1.22

prow/manifests/overlays/metal3/config.yaml
Since golang 1.20 is already deprecated
This is needed for PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1858
=> Test capm3 release 1.6 with golang 1.22

jenkins/image_building/dib_elements/ubuntu-node/post-install.d/90-pre-pull-images
In Ubuntu e2e tests calico-node pods are stuck in `CrashLoopBackOff` because of missing `localhost` in `/etc/hosts` file this PR is fixing it.
calico-node error:
`kubelet  Liveness probe failed: calico/node is not ready: Felix is not live: Get "http://localhost:9099/liveness": dial tcp: lookup localhost on 8.8.8.8:53: no such host`
=> 🌱 Fix Calico CrashLoopBackOff in ubuntu e2e tests

prow/manifests/overlays/metal3/config.yaml
Golang 1.20 is deprecated so let's move bmo release 0.5 testing to go 1.22
Needed for [PR](https://github.com/metal3-io/baremetal-operator/pull/1827)
=> Test bmo release 0.5 with golang 1.22

prow/manifests/overlays/metal3/config.yaml
Update the config to test ipam release 1.6 with golang 1.22, this is needed for following [PR](https://github.com/metal3-io/ip-address-manager/pull/616)
=> Test ipam release 1.6 with golang 1.22

.github/workflows/container-image-build.yml
This template is not meant to be used in this repo, but to be referenced by container build wf from other repos.
An example of how it could be used: https://github.com/metal3-io/baremetal-operator/actions/runs/10280659565/job/28448467379?pr=1861
=> :seedling: Add container image build wf template

jenkins/image_building/build-image.sh
Uplifts Uplift kubernetes version to v1.31.0 for image building. Also uplifts crio and crictl
Part of: https://github.com/metal3-io/cluster-api-provider-metal3/issues/1887
=> Uplift kubernetes version to v1.31.0 for image building

jenkins/image_building/build-image.sh, jenkins/image_building/upload-node-image.sh, jenkins/image_building/verify-node-image.sh, jenkins/jobs/image_building.pipeline, jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
This is to split ubuntu and centos image building into separate VMs and have proper indication for each step results in Jenkins UI.
=> :seedling: Change image-building pipeline to a matrix

jenkins/image_building/build-image.sh
This helps solve the ongoing failure in [node-image-building job](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_periodic_node_image_building/)
https://jenkins.nordix.org/blue/organizations/jenkins/metal3_periodic_node_image_building/detail/metal3_periodic_node_image_building/78/pipeline/
In general, this PR improves the script by:
- Removing global scope pip install (`sudo pip3 install`), which is not recommended by PEP8, and will stop working in later Python version.
- Removing unnecessary installation of package `python-openstackclient`
- Removing unnecessary clone of `diskimage-builder` repo
- Using `python-venv` (a python standard library) instead of `virtualenv` (package from PyPI).
- Minor syntax updates.
=> :seedling: Add python3-dev package to build-image.sh

jenkins/image_building/build-image.sh, jenkins/image_building/upload-ci-image.sh, jenkins/jobs/image_building.pipeline
In node image build, we have changed the pipeline so that building and uploading images happen in different jenkins stages. This PR updates the ci-image build, which also uses the same pipeline, to that schema.
This change was tested on:
https://jenkins.nordix.org/blue/organizations/jenkins/metal3_periodic_ci_image_building/detail/metal3_periodic_ci_image_building/59/pipeline/
and
https://jenkins.nordix.org/blue/organizations/jenkins/metal3_periodic_node_image_building/detail/metal3_periodic_node_image_building/79/pipeline/93/
=> :seedling: Adapt ci-image wf to image-build pipeline

prow/manifests/overlays/metal3/config.yaml
Most of tests in prow config file are grouped by the test names, but some of them are currently grouped by branch names (for e.g. `metal3-centos-e2e-feature-test-release-1-7-pivoting` is grouped with `metal3-centos-e2e-feature-test-release-1-7-features`, instead of `metal3-centos-e2e-feature-test-main-pivoting`). This makes it difficult to manage the tests, for e.g. when adding/removing test branches.
This PR regroups the tests so that all of them are grouped by tests.
=> :seedling: Regroup prow config tests by names

prow/manifests/overlays/metal3/config.yaml
As we accidentally published BMO v0.8.0-rc.0 instead of v0.7.0-rc.0, we decided to skip release-0.7 and jump directly to release-0.8.
=> :seedling: Change BMO release-0.7 to release-0.8

jenkins/jobs/image_building.pipeline
This PR moves image building jobs to private cloud by changing jenkins worker label. 
Tested here:
Node image building https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_periodic_node_image_building/84/
CI image building https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_periodic_ci_image_building/62/
=> Move image building jobs to private cloud

jenkins/jobs/capm3-e2e-tests.pipeline, jenkins/jobs/e2e_features_test.pipeline
This PR moves k8s upgrade and e2e other features(not including remediation and pivoting) tests to private cloud.
tested here:
k8s upgrade - https://jenkins.nordix.org/job/metal3-e2e-1-29-1-30-upgrade-test-release-1-7/8/
features https://jenkins.nordix.org/job/metal3-centos-e2e-feature-test-release-1-7-features/11
=> Move k8s upgrade and e2e other feature tests to private cloud

prow/README.md, prow/infra/kustomization.yaml, prow/manifests/overlays/metal3/kustomization.yaml
Bump Ingress-Nginx to v1.10.4 because of a severity CVE on v1.10.1
This PR also:
- Fix cloud reference in prow README
- Update prow overlays to new kustomize syntax.
=> 🌱 Bump ingress-nginx in prow to v1.10.4

jenkins/image_building/upload-ci-image.sh
This PR makes sure that the latest image created in Openstack is pushed under a common name. This will make sure that the image being used in Jenkins workers remain active all the time. When replacing an old image with the latest, this commit also renames the old image based on its original name which is build date suffixed and this will be added in the images as an image_name property.
=> Allow uploading the latest image under a common name

.github/workflows/pr-verifier.yaml
This workflow will be used to replace `Kubebuilder-release-tools pr-verifier`. It can be referenced to in all of our repos.
Example of how this workflow can be used: https://github.com/metal3-io/baremetal-operator/pull/1968
=> :seedling: Add pr-verifier-workflow

.github/dependabot.yml
We have now multiple reusable github actions hosted via project-infra so we also need Dependabot config to keep the up to date.
=> add dependabot config for github actions bumps

.github/workflows/build-images-action.yml
Add missing dockerfile-directory input for basic-checks image build, which was added in #865
=> add missing dockerfile-directory for basic-checks

.github/workflows/build-images-action.yml
Add reusable container build file as trigger file path for the build-image-action.
=> add reusable container build as trigger file path

jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-luks-tpm-support/install.d/99-install-luks-tpm, jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-lvm-support/install.d/99-install-lvm2
This commit ads elements to support the installation of:
- tpm2_tools
- cryptsetup
- lvm2
=> Add support for lvm, cryptsetup, tpm2_tools

hack/markdownlint.sh, prow/manifests/overlays/metal3/config.yaml
Bump markdownlint-cli2 to v0.12.0 both in local markdownlint script and in prow config for all repos.
=> bump markdownlint-cli2 to v0.12.0

prow/manifests/overlays/metal3/config.yaml
It contains some bug fixes since previous version v8.9.0.
No fixes to spellings needed.
Repo specific implementations to be merged after this:
- https://github.com/metal3-io/metal3-docs/pull/474
- https://github.com/metal3-io/metal3-io.github.io/pull/488
=> bump cspell to v8.13.3

jenkins/image_building/initrd_sdk/README.md, jenkins/image_building/initrd_sdk/unseal-and-open-luks.service, jenkins/image_building/initrd_sdk/verify-realroot.sh
This commit adds:
- New script used to avoid race conditions while running root switching
- New systemd unit file that is used to run the previously introduced unlock-mount-luks.sh
- Documentation about the new files
=> extending the initrd_sdk

prow/container-images/basic-checks/Dockerfile
Bump golang to 1.22.8 in basic-checks image.
=> bump golang to 1.22.8 in basic-checks image

jenkins/image_building/initrd_sdk/README.md
This commit:
- Fixes a typo in the README file of the initrd_sdk
=> fix typo in initrd_sdk

jenkins/image_building/initrd_sdk/unlock-mount-luks.sh, jenkins/image_building/initrd_sdk/verify-realroot.sh
This commit adds the following changes:
- Implements a feature for the initrd sdk that makes it possible to verify that both the root and the config drive partitions have been decrypted.
- Now the verify script is reading /dev/zero in order to generate the 1s delay, instead of reading from interactive stdin. In environments where the verify script is executed in the background or by other services e.g. cron, systemd etc... the read command returns immediately thus not providing sufficient delay.
=> improve initrd verification logic

jenkins/jobs/capm3-e2e-tests.pipeline
Ephemeral tests are taking more than 5 hours. This PR is changing the timeout of Ephemeral tests to 6 hours.
ref: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-centos-e2e-ephemeral-test-main/44/console
=> 🌱 Increasing timeout of ephemeral tests

jenkins/image_building/upload-node-image.sh, jenkins/scripts/artifactory/utils.sh
Jenkins job did not fail when curl upload file failed, it finished successfull eenthough images were not uploaded. 
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_periodic_node_image_building/97/consoleFull
```
{
"errors" : [ {
"status" : 403,
"message" : "Login has failed. Due to Incorrect username/password or locked user."
} ]
```
This PR fixes this issue.
Also corrects number comparison conditions.
=> Catch curl upload error when upload fails

.gitignore, jenkins/image_building/initrd_sdk/test_unlock_config, jenkins/image_building/initrd_sdk/tpm2-unseal-key.sh, jenkins/image_building/initrd_sdk/unlock-mount-luks.sh, jenkins/image_building/initrd_sdk/unseal-and-open-luks.service, jenkins/image_building/initrd_sdk/verify-realroot.sh
This commit:
- Implements LUKS and TPM2 tool chain checks and enforcement in order to
avoid issues originating from uninitialized hardware and driver modules.
- Improves the "testability" of the code
- Changes the configuration workflow of the unlock-mount-luks.sh to
rely on a config file instead of positional cmdline arguments in order
to make configuration more explicit and easier to debug.
- Ads script used for tpm2.0 persistent secret unsealing
- Ads a config file with value presets intended for testing
- Implements support for disks where only the root partition need decryption
by the unlock-mount-luks.sh
- Implements auto discovery for root partition based on GPT partition label
- Implements auto discovery for config drive partition based on GPT partition
label
- Implement support …
=> improve robustness of the initrd sdk

prow/README.md, prow/config/jobs/metal3-io/baremetal-operator-release-0.5.yaml, prow/config/jobs/metal3-io/baremetal-operator-release-0.6.yaml, prow/config/jobs/metal3-io/baremetal-operator-release-0.8.yaml, prow/config/jobs/metal3-io/baremetal-operator.yaml, prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml, prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.6.yaml, prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.7.yaml, prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.8.yaml, prow/config/jobs/metal3-io/ip-address-manager-release-1.6.yaml, prow/config/jobs/metal3-io/ip-address-manager-release-1.7.yaml, prow/config/jobs/metal3-io/ip-address-manager-release-1.8.yaml, prow/config/jobs/metal3-io/ip-address-manager.yaml, prow/config/jobs/metal3-io/ironic-image-release-24.0.yaml, prow/config/jobs/metal3-io/ironic-image-release-24.1.yaml, prow/config/jobs/metal3-io/ironic-image-release-25.0.yaml, prow/config/jobs/metal3-io/ironic-image-release-26.0.yaml, prow/config/jobs/metal3-io/ironic-image.yaml
In the previous PR I kept "common" tests in the main file. This PR splits them up so that each release branch has all its own tests clearly defined in a separate file. Easier to keep track of at the cost of some duplication.
=> Prow: Define jobs per release branch

prow/config/plugins.yaml
This plugin will apply milstones automatically to merged PRs depending on what branch they target.
Fixes: #807
=> Prow: Configure milestone applier plugin

prow/config/plugins.yaml
Now it should match [the actual milestones](https://github.com/orgs/metal3-io/projects/8/views/4).
=> Prow: Fix milestone applier config

jenkins/image_building/upload-ci-image.sh
Fixes: #885 
The issue was in the output of the `openstack image show` command, which was not having proper format that we want. So changing it to json is giving correct output.
=> Fix CI image upload issue

prow/capo-cluster/infra-kct.yaml, prow/capo-cluster/kubeadmconfigtemplate.yaml, prow/capo-cluster/kubeadmcontrolplane.yaml
There has been a change in the data received by the metadata service in xerces. This made the templated values in the KCP and KCT invalid. This commit updates the templates with the new cloud-init structure.
The "v1" keys that we are using now should be stable. They are documented here: https://cloudinit.readthedocs.io/en/latest/explanation/instancedata.html#standardised-instance-data-json-v1-keys
=> Update KCT and KCP with new cloud-init structure

prow/README.md, prow/capo-cluster/infra-md.yaml, prow/capo-cluster/kubeadmcontrolplane.yaml, prow/capo-cluster/machinedeployment.yaml, prow/capo-cluster/openstackmachinetemplates.yaml
This upgrades Kubernetes to v1.30.6, CAPI to v1.8.5 and CAPO to v0.11.1.
=> Prow: Upgrade Kubernetes and CAPI/CAPO

prow/capo-cluster/machinedeployment.yaml, prow/cluster-resources/autoscaler.yaml, prow/cluster-resources/kustomization.yaml
Also adjust minimum number of machines in the worker MD.
The cloud-provider and autoscaler bump should really have
happened together with the kubernetes bump but was forgotten.
=> Prow: Bump calico, autoscaler and cloud-provider

prow/cluster-resources/autoscaler.yaml
There is a bug in the autoscaler that makes it get stuck on a permission
issue sometimes. It doesn't really need these permissions for our
use-case, but adding them should hopefully avoid it getting stuck.
See https://github.com/kubernetes/autoscaler/issues/6490
Fixes: #881
=> Prow: Temporary autoscaler RBAC workaround

jenkins/jobs/capm3-e2e-tests.pipeline
This PR moves agent creation outside the stage, ensuring it doesn't time out. This change reduces timeout failures in tests, especially when the infrastructure is slow. Additionally, it aligns the agent creation process with other pipeline scripts for consistency.
=> 🌱 Fixing agent creation timeout issue

.github/workflows/build-images-action.yml, prow/container-images/basic-checks/Dockerfile
Update baseimage when we build the basic-checks image. While we usually bump to quite new version, we also have repository_dispatch trigger in the workflow, so we can rebuild the image in which case baseimage is old and should get updated.
Quay is reporting a lot of vulnerabilities for this image already.
=> update basic-checks baseimage when building it

prow/config/jobs/metal3-io/baremetal-operator-release-0.8.yaml, prow/config/jobs/metal3-io/baremetal-operator.yaml, prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml, prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.8.yaml, prow/config/jobs/metal3-io/ip-address-manager-release-1.8.yaml, prow/config/jobs/metal3-io/ip-address-manager.yaml, prow/config/jobs/metal3-io/ironic-standalone-operator.yaml
Bump prow tests go use golang:1.23 and basic-checks:1.23, as now Golang bumps are completed.
=> bump prow tests to Go 1.23

prow/Makefile, prow/config/config.yaml, prow/config/generic-autobumper-config.yaml, prow/config/jobs/metal3-io/project-infra.yaml, prow/config/jobs/periodics.yaml, prow/manifests/base/crier.yaml, prow/manifests/base/deck.yaml, prow/manifests/base/ghproxy.yaml, prow/manifests/base/hook.yaml, prow/manifests/base/horologium.yaml, prow/manifests/base/prow-controller-manager.yaml, prow/manifests/base/sinker.yaml, prow/manifests/base/statusreconciler.yaml, prow/manifests/base/tide.yaml, prow/manifests/overlays/metal3/external-plugins/cherrypicker_deployment.yaml, prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml, prow/manifests/overlays/metal3/external-plugins/labels_cronjob.yaml, prow/manifests/overlays/metal3/external-plugins/needs-rebase_deployment.yaml
The GCR is about to be shut down. Prow already stopped publishing images there but have not transitioned to registry.k8s.io yet. Because of this we are switching to use the staging registry instead, which is the same that the k/k prow is also using.
Related to #871 (doesn't fix, since the issue is for migrating to registry.k8s.io)
=> Prow: Switch to staging registry

prow/config/generic-autobumper-config.yaml
The autobumper is not checking Makefiles unless explicitly configured to do so. I have tested this with a dry-run locally.
=> Prow: Add Makefile to autobumper

prow/config/generic-autobumper-config.yaml, prow/config/jobs/periodics.yaml, prow/manifests/overlays/metal3/external-plugins/labels_cronjob.yaml
These components are not maintained in the new prow repo and have apparently not been pushed to the same staging registry. Instead they are pushed to the test-infra staging registry in GCR.
This commit changes the registry for the commenter and label_sync jobs and updates the autobumper to detect these images as well. I also had to bump the tag of the images since they have not pushed old image to the same registry.
=> Prow: Use GCR for commenter and label_sync images

prow/README.md
There has been a change upstream that makes it necessary to specify the protocol (http or https) for the s3 endpoint.
=> Prow: Update docs

.cspell-config.json, prow/README.md, prow/capi/bootstrap.yaml, prow/capi/control-plane.yaml, prow/capi/core.yaml, prow/capi/infrastructure.yaml, prow/capi/kustomization.yaml
We have so far been relying on imperative commands to manage the lifecycle of CAPI/CAPO and cert-manager. This commit introduces the CAPI Operator with manifests to declaratively manage these components instead.
Fixes: #907
=> Prow: Use CAPI Operator

hack/prow_test_dumper.py
Improve `prow_test_dumper.py` not only to dump test settings from Prow's `config.yaml`, to actually crosscheck versus GitHub branch protections. This highlights any mismatches we might have, accounting for both missing but also extra checks.
Also, set defaults to metal3-io file locations so `--job-dir` and `--config` do not need to be input in our use case. Make `--config` also flag and not positional arg.
`GITHUB_TOKEN` must be exported or supplied via `--token`, and it must have maintainer rights to read branchprotection settings. Using token without sufficient rights lead to erroring out.
This reveals we have one misconfigured branch in CAPM3/release-1.6 branch (irrelevant as it is EOS, not fixing it until this is merged, so it can work as POC this works).
Output in case of misconfigs: …
=> Improve Prow test dumper script to crosscheck settings with GitHub branchprotections

prow/config/plugins.yaml
Nordix support repos could use blunderbuss as well.
=> add blunderbuss to Nordix repos

prow/capo-cluster/infra-md.yaml, prow/capo-cluster/kubeadmcontrolplane.yaml, prow/capo-cluster/machinedeployment.yaml, prow/capo-cluster/openstackmachinetemplates.yaml
To improve performance and reduce the risk of network issues due to volumes mounted over network, we switch to flavors with local disk. Root volumes are no longer needed.
Fixes: #922
=> Prow: Use flavors with local disk

.github/workflows/container-image-build.yml
This PR adds a custom inputs, which can be used to pass a custom git ref to the container build workflow. ref_name and sha references will be updated accordingly.
In case the input is not available, the workflow still uses `github.ref` `github.ref_name` and `github.sha`, which is the current behavior.
=> :seedling: Add custom ref input to container build workflow

jenkins/image_building/build-image.sh
Bump k8s to 1.32.0, crictl to 1.32.0 and crio to 1.31.3
=> :seedling: Bump k8s to 1.32.0, crictl to 1.32.0 and crio to 1.31.3

jenkins/README.md, prow/config/jobs/metal3-io/ironic-ipa-downloader.yaml, prow/config/jobs/metal3-io/mariadb-image.yaml, prow/config/jobs/metal3-io/metal3-dev-env.yaml, prow/config/plugins.yaml
Add release-1.9 triggers to dev-env, ipa-downloader and mariadb-image.
Update README.md for the new triggers.
Update milestone applier config to use 1.9 branches and milestones correctly.
=> add release-1.9 triggers to other repos

prow/config/jobs/metal3-io/metal3-dev-env.yaml
We have 1.9 and 1.8 both enabled now. 1.9 test is working, so remove old 1.8.
=> remove old 1.8 tests from required for dev-env

prow/config/jobs/metal3-io/ironic-image-release-27.0.yaml
Run ironic-image 27.0 tests versus release-1.9.
=> run ironic-image 27.0 tests versus release-1.9

.github/workflows/pr-verifier.yaml
This commit:
- Changes the PR title in the PR verifier script to be a constant string in the BASH context.
=> :bug: fix incorrect PR title handling

jenkins/scripts/dynamic_worker_workflow/build_ipa.sh
This commit:
- Fixes an icorrect value assignment for IPA repository refference This bug was causing the build tooling to not check out the specified IPA branch instead it was checking out the mian
- Adds missing IPA repository address variable
=> fix IPA git commit/branch refference

jenkins/jobs/capm3-e2e-tests.pipeline
As we want to test more clusters in scalability, the default 3h is not enough. For now let's set it to 6h, but the timeout could be extended even further in the future.
=> :seedling: Set scalability test timeout to 6h

prow/config/jobs/metal3-io/baremetal-operator.yaml, prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml, prow/config/jobs/metal3-io/ip-address-manager.yaml, prow/config/jobs/metal3-io/ironic-standalone-operator.yaml
Bump kubeconform in manifestlint job to v0.6.7.
Add missing IRSO manifestlint prow job. The script is already in IRSO repo but prow job was missing.
There are no failures in target repos due to bump, will not backport the bump to release branches.
=> bump kubeconform/manifestlint to v0.6.7

jenkins/scripts/dynamic_worker_workflow/build_ipa.sh, jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-cleanup-dracut/finalise.d/99-delete-dracut
this PR:
- removes the dracut packages from the rootfs
The size of the IPA image is slowly but steadily growing, and in order to minimize the size of the image some packages could be removed.
Although dracut is used at some point in the DIB build process there  is no point leaving it in the root file system after the IPA build process is finished. IPA user space does not rely on dracut, systemd can handle everything on it's own.
=> remove dracut from the IPA rootfs

prow/config/jobs/metal3-io/mariadb-image.yaml
Runmariadb script is not a trigger for shellcheck prow job in mariadb-image. Add it.
Another PR is made to mariadb-image to fix the actual shellcheck script.
=> add runmariadb script as a shellcheck trigger for mariadb-image

jenkins/jobs/capm3-e2e-tests.pipeline
The two pipelines don't differ much, hence one could merge to the other. For now we merge everything into capm3-e2e-tests pipeline. The other pipeline will be removed once we make sure everything works fine.
=> :seedling: Merge e2e_features_test to capm3-e2e-tests pipeline

jenkins/jobs/dynamic_fullstack_building.pipeline, jenkins/scripts/dynamic_worker_workflow/fullstack.sh, prow/config/jobs/metal3-io/project-infra.yaml
This PR:
- Converts the previously mostly unused and outdated project_infra
fullstack PR jobs to use prow triggers instead of "ghprb" triggers
- Makes both the periodic and the PR fullstack jobs use the same prow
compatible pipeline script
- Removes the variable related to IPA git reference from the fullstack
wrapper script as the IPA builder uses the branch name as reference.
This change is needed because the Metal3-io project does no longer uses the
Jenkins ghprb plugin, instead the PR jobs are triggered via GitHub or Prow.
=> convert fullstack jobs to be prow compatible

prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.9.yaml, prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
This commit adds the new scalability tests to prow
=> :seedling: Add scalability test prow triggers

prow/README.md, prow/capi/bootstrap.yaml, prow/capi/control-plane.yaml, prow/capi/core.yaml, prow/capi/infrastructure.yaml, prow/capi/kustomization.yaml, prow/capi/toleration-node-selector-patch.yaml
Make sure that all CAPI related components run on the infra nodes by adding tolerations and nodeSelectors to them.
Bump cert-manager and CAPI operator versions and update README to always use the operator way of deploying CAPI providers.
Bump CAPI core, KBT and KCP to v1.9.5 and CAPO to v0.12.1.
CAPO has a new external dependency, ORC, so this is also added, plus tolerations and nodeSelector for it.
Changes are already applied in the cluster.
=> Prow: Add tolerations and nodeSelectors for CAPI related components and bump versions

prow/capo-cluster/infra-md.yaml, prow/capo-cluster/kubeadmcontrolplane.yaml, prow/capo-cluster/machinedeployment.yaml, prow/capo-cluster/openstackcluster.yaml, prow/capo-cluster/openstackmachinetemplates.yaml, prow/cluster-resources/autoscaler.yaml, prow/cluster-resources/kustomization.yaml, prow/infra/add-args.yaml, prow/infra/configmap-patch.yaml, prow/infra/kustomization.yaml
See individual commit messages for more details.
This PR does the following:
- Upgrade ingress-nginx to v1.12.0
- Upgrade Calico
- Upgrade cloud-provider integrations and cluster-autoscaler
- Upgrade kubernetes to v1.31.6
- Upgrade nodes and bastion to Ubuntu 24.04
The changes are already applied.
=> Prow: Upgrade kubernetes, ingress, calico and more

prow/container-images/basic-checks/Dockerfile
We need basic-checks bumped to 1.23.7.
=> bump basic-checks image to golang 1.23.7

jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml, jenkins/scripts/bml_cleanup.sh, jenkins/scripts/bml_integration_test.sh, jenkins/scripts/files/run_clean.sh, jenkins/scripts/files/run_integration_tests.sh
This PR moves provisioning cluster (minikube) from bare metal server to virtual machine that serves as jenkins agent
=> move provisioning cluster to jenkins agent in bml

hack/prow_test_dumper.py
In case a branch is not having any branch protection (it is not defined at all, or matching any branch protection wildcards), we just exited before. Now, it will return empty set, so we correctly get notified that tests are missing, and also the processing continues to further jobs defined.
=> prow-test-dumper: handle completely missing branch protection case

jenkins/jobs/bmo_e2e_optional_tests.pipeline, prow/config/jobs/metal3-io/baremetal-operator-release-0.8.yaml, prow/config/jobs/metal3-io/baremetal-operator-release-0.9.yaml, prow/config/jobs/metal3-io/baremetal-operator.yaml
Optional BMO e2e tests have been running as periodic jobs by Github agents, adding only the pull jobs so that they can be triggered on PRs as well.
=> :seedling: Add pull bmo e2e optional to prow

prow/manifests/base/ghproxy.yaml
GHProxy has been logging warnings about a legacy option. This commit disables it. The log message suggests that smaller prow instances can set this flag to false unconditionally, so it should work well for us. This is what the warnings look like:
```
{"component":"ghproxy","file":"sigs.k8s.io/prow/cmd/ghproxy/ghproxy.go:173","func":"main.main","level":"warning","msg":"The deprecated `--legacy-disable-disk-cache-partitions-by-auth-header` flags value is `true`. If you are a bigger Prow setup, you should copy your existing cache directory to the directory mentioned in the `Not using a partitioned cache because legacyDisablePartitioningByAuthHeader is true` messages to warm up the partitioned-by-auth-header cache, then set the flag to false. If you are a smaller Prow setup or just started …
```
=> Prow: Disable legacy cache option

jenkins/jobs/bml_integration_tests.pipeline, jenkins/jobs/bmo_e2e_optional_tests.pipeline, jenkins/jobs/capm3-e2e-tests.pipeline, jenkins/jobs/clean_resources.pipeline, jenkins/jobs/dev_env_integration_tests.pipeline, jenkins/jobs/dynamic_fullstack_building.pipeline, jenkins/jobs/e2e_features_test.pipeline, jenkins/jobs/image_building.pipeline
We have been using username/password for checking out all repos. This is not necessary for public repos and doesn't seem to make any difference. The password has been changed without impacting any of the jobs... so this commit removes the use of these credentials.
=> Remove unnecessary git credentials

.github/workflows/container-image-build.yml
https://github.com/metal3-io/ironic-image/issues/615
=> Enables optionally multiplatform container builds

jenkins/image_building/build-image.sh, jenkins/image_building/upload-ci-image.sh, jenkins/image_building/verify-ci-image.sh, jenkins/jobs/image_building.pipeline, prow/config/jobs/metal3-io/project-infra.yaml
Related gerrit change: https://gerrit.nordix.org/c/infra/cicd/+/23399
Enable triggering image building jobs on PRs
Verify CI images by uploading them with a "-staging" suffix first, run a
basic integration test using this staging image before proceeding to make
it the latest.
Fixes: #985
=> Image build job with test

jenkins/jobs/image_building.pipeline
When triggering jobs on PRs, we need to include the PR commit(s) in the refspec. Otherwise we cannot checkout the relevant code.
=> Fix image build refspec for PR jobs

prow/config/jobs/metal3-io/ironic-standalone-operator.yaml
IRSO needs golang 1.24 for mariadb-operator, so we need to bump it here as well. Other repos will follow when 1.10 cycle etc are done.
/cc @dtantsur @lentzi90
=> bump golang to 1.24 for IRSO

jenkins/image_building/upload-ci-image.sh, jenkins/jobs/image_building.pipeline
When triggering jobs on PRs, we need to include the PR commit(s) in the
refspec. Otherwise we cannot checkout the relevant code. Pre-build-merge
is also removed to keep the behavior similar to other jobs.
This commit also avoids uploading images from PR tests and making them "latest".
It also fixes the labels for the CI image verification step so that the
label is separate for ubuntu and centos images.
Last but not least, this tweaks the logic for image retention.
CI images are uploaded as metal3-ci-<os>-staging for verification.
In periodic jobs, the staging images are then renamed to *-latest after
successful verification. This is not done in PR jobs.
Any existing *-staging images are deleted before uploading a new.
Otherwise we risk mixing them up with the previously used CI images and …
=> Fix image building refspec and upload

prow/config/config.yaml
If we trigger optional jobs on a PR, this makes sure that prow won't merge it unless they actually pass. Otherwise, prow will happily ignore these jobs and merge as long as the required jobs have passed.
=> Prow: Require manually triggered jobs

jenkins/image_building/dib_elements/centos-node/pre-install.d/55-setup-repos, jenkins/image_building/dib_elements/ubuntu-node/pre-install.d/55-setup-repos
CRI-O has moved from being a k8s add on project to its own subproject. Hence new patch installations would fail if we dont point towards the correct stable repositories to download release binaries.
=> Update CRIO installation link from k8s addons to CRI'o own subproject

jenkins/jobs/image_building.pipeline
Docs: https://www.jenkins.io/doc/book/pipeline/syntax/#evaluating-when-before-entering-agent-in-a-stage
Without this, we end up blocked waiting for the agent to come up before the when block is evaluated. The agent never comes up since there is no image unless we are doing a CI image job.
=> Evaluate when block before agent in CI image verification

jenkins/image_building/dib_elements/centos-node/pre-install.d/55-setup-repos
Had the add the clean cache steps since the repo was not found previously but now it is taking too much time to update the repos after the cleaned cache. Lets see if this is at all needed now.
=> Don't clean the yum cache while building CentOS node image

prow/container-images/basic-checks/Dockerfile
Bump basic-checks image to 1.23.8 as some PRs need it in BMO, such as https://github.com/metal3-io/baremetal-operator/pull/2433.
=> bump basic-checks image to 1.23.8

prow/config/jobs/metal3-io/ip-address-manager-release-1.10.yaml
Remove centos e2e as required test from release-1.10 branch. We only run ubuntu suite in release branches.
=> remove centos e2e from required in 1.10 branch

jenkins/jobs/image_building.pipeline
We need to install openstack client before doing this step (as we already do when we upload the staging image).
=> Fix CI image upload

.github/workflows/pr-link-check.yml, .github/workflows/scheduled-link-check.yml, .lycheeignore, jenkins/README.md, jenkins/scripts/bare_metal_lab/README.md, prow/README.md
These workflows can be called from the other Metal3 repos to test for broken links. 
`.github/workflows/broken-link-check.yml `is for testing all md files in a repo
`.github/workflows/pr-link-check.yml` is for testing all `.md` files that have changed in a PR. This does not check all files but only the ones that have changed.
I've tested the pr workflow in situations listed below and it is giving the output I expect
- .md file is edited and doesn't have any link (pass)
- .md file is edited and has working links (pass)
- .md file is edited and has broken link (fail)
-  pr does not have any edited .md files (pass)
Fixes broken links.
=> :seedling: Add broken link check: pr and scheduled

.github/workflows/pr-link-check.yml, .github/workflows/scheduled-link-check.yml
ix how Github token is used in link checks workflow
=> :seedling: Fix how Github token is used in link checks workflow

.github/workflows/pr-link-check.yml
Tweak PR link check args. In this PR I set the values to be the same as are in scheduled workflow. 
Set user agent to help being detected as a bot: `--user-agent "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0"`
Make sure relative paths work by setting root directory:   `--root-dir "$(pwd)/"`
Github, mdbook and such recognize paths with out file extensions, set a fallback so that links with out file extensions are handled correctly:   `--fallback-extensions "md"`
=> Tweak PR link check args

.github/workflows/container-image-build.yml
Since merging the labeling PR, it also moved the defaults tags in a way for main that they are empty. Fix that.
=> fix container tags for main

.github/workflows/build-images-action.yml, prow/container-images/basic-checks/Dockerfile
Bump basic-checks image to golang:1.24.3 to support bumping golang in BMO later. This new image is not used by anyone or changing anything, until BMO and its prow jobs are bumped to Go 1.24. This is just pre-building the image, so it doesn't explode when we do.
=> bump basic-checks image to golang:1.24.3

prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.10.yaml, prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.9.yaml
Bumps go for the prow tests for CAPM3 release-1.10 and release-1.9
=> Bump CAPM3 release branch prow jobs to use go v1.24

prow/config/jobs/metal3-io/baremetal-operator-release-0.10.yaml, prow/config/jobs/metal3-io/baremetal-operator-release-0.9.yaml, prow/config/jobs/metal3-io/baremetal-operator.yaml
Bumps golang to v1.24 for prow jobs for following branches
- main
- release 0.10
- release 0.9
=> Bump BMO prow jobs to use go v1.24

prow/config/jobs/metal3-io/ip-address-manager-release-1.10.yaml, prow/config/jobs/metal3-io/ip-address-manager-release-1.9.yaml, prow/config/jobs/metal3-io/ip-address-manager.yaml
Bumps golang to v1.24 for prow jobs for following branches
- main
- release 1.10
- release 1.9
=> Bump IPAM prow jobs to use go v1.24

prow/config/config.yaml
This reverts commit ad608465e1b35624000c998d46163def0d958334.
This does not do what we wanted it to do, let's revert it. It just acts as double branch protection, possibly causing it to re-run the contexts for no reason.
=> Revert "Prow: Require manually triggered jobs"

prow/config/jobs/metal3-io/ironic-standalone-operator-main.yaml, prow/config/jobs/metal3-io/ironic-standalone-operator-release-0.4.yaml
Add IRSO release-0.4 Prow jobs and rename the main job to match other repos.
Ref: https://github.com/metal3-io/ironic-standalone-operator/pull/211
=> add IRSO 0.4 prow jobs

jenkins/jobs/capm3-e2e-tests.pipeline, prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml, prow/config/jobs/metal3-io/metal3-dev-env.yaml, prow/config/jobs/metal3-io/project-infra.yaml
Add timeout and agent_label to use with MachineDeployment tests adopted from CAPI. Add also Prow keywords to start the job from PRs.
=> Add CAPI md tests' setup and Prow keywords

prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml, prow/config/jobs/metal3-io/metal3-dev-env.yaml, prow/config/jobs/metal3-io/project-infra.yaml
Add Prow keywords to run K8s conformance tests from PRs in CAPM3, metal3-dev-env and project-infra.
=> Add Prow keywords for conformance tests

prow/config/plugins.yaml
Update IRSO milestones (which have been completely wrong since 0.2 ...)
/hold
This can be merged only after 0.4 branch is created.
=> update IRSO milestones

prow/README.md, prow/capo-cluster/infra-md.yaml, prow/capo-cluster/kubeadmcontrolplane.yaml, prow/capo-cluster/machinedeployment.yaml, prow/capo-cluster/openstackmachinetemplates.yaml, prow/cluster-resources/kustomization.yaml, prow/infra/kustomization.yaml
- Kubernetes v1.32.5, autoscaler and cloud provider also bumped to v1.32
- Calico bumped to v3.30.1
- Ingress-nginx v1.12.3
The `cloud-provider` flag no longer exists in the API server, so this has been removed.
=> Prow: Bump kubernetes, calico and ingress-nginx

prow/config/jobs/metal3-io/baremetal-operator.yaml, prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml, prow/config/jobs/metal3-io/ip-address-manager.yaml, prow/config/jobs/metal3-io/metal3-dev-env.yaml, prow/config/jobs/metal3-io/project-infra.yaml
Add prow keywords for k8s pre-release testing for BMO, IPAM and CAPM3 and update the naming for project-infra.
=> Add prow keywords for k8s pre-release testing

jenkins/image_building/build-image.sh, jenkins/jobs/pre_release_tests.pipeline
Fetch the latest pre-release Kubernetes version for a specified minor version. This is to require less manual changes.
=> Automatically fetch latest pre-release k8s version

jenkins/jobs/bmo_e2e_optional_tests.pipeline
BMO optional tests need more time to complete the jobs. It didn't have any other errors than timeout. So by increasing the time of tests would solve our issue.
=> Increase BMO optional tests timeout

jenkins/jobs/image_building.pipeline
Start building opensuse images in the CI. At least node image is required to test opensuse in the CI.
=> Add OpenSUSE leap image to image building job
