- prow/config/config.yaml
Depends on https://github.com/metal3-io/metal3-dev-env/pull/75
> Use shellcheck script in metal3-dev-env.

- prow/config/config.yaml
Now that this job is passing, run it automatically on all PRs.
> Always run shellcheck job on metal3-dev-env.

- OWNERS
I turned on tide for this repo, but can't lgtm my own PRs to merge
them.  :-)
> OWNERS: Add more approvers and reviewers.

- prow/config/config.yaml
due to the switch to v1alpha2 in master
> Update images for capbm unit tests

- jenkins/OWNERS
- jenkins/README.md
- jenkins/jobs/integration_tests.pipeline
- jenkins/scripts/files/run_integration_tests.sh
- jenkins/scripts/integration_delete.sh
- jenkins/scripts/integration_test.sh
- jenkins/scripts/utils.sh
/assign @russellb 
/cc @stbenjam
> Add Jenkins pipeline and scripts for E2E Nordix tests

- prow/config/config.yaml
required for v1alpha3
/assign @russellb
> Update go image to 1.13 for CAPBM tests

- jenkins/scripts/files/run_integration_tests.sh
This is linked to https://github.com/metal3-io/metal3-dev-env/pull/239 and https://github.com/metal3-io/cluster-api-provider-baremetal/issues/267
> Jenkins: Rename CAPBM to CAPM3

- jenkins/README.md
Update CI doc based on [#58](https://github.com/metal3-io/project-infra/pull/58).
> Update CI doc based on #58

- jenkins/README.md
- jenkins/scripts/files/run_integration_tests.sh
- prow/config/config.yaml
- prow/config/plugins.yaml
This adds the CI to the new repository cluster-api-provider-metal3
> Add cluster-api-provider-metal3 repo in Prow and Jenkins config

- jenkins/scripts/files/run_integration_tests.sh
reflect the changes in metal3-dev-env
/hold until https://github.com/metal3-io/metal3-dev-env/pull/250 is merged
/cc fmuyassarov
> Jenkins e2e test is v1a3 by default

- jenkins/scripts/files/run_integration_tests.sh
The current condition did not match.
/cc @fmuyassarov 
/cc @kashifest
> Jenkins fix condition to avoid merge

- jenkins/scripts/files/run_integration_tests.sh
> Replaces management cluster in CI when CI host is Ubuntu

- prow/config/config.yaml
Add a job to run the new generation test for the baremetal-operator
repository using the image and tools added in
https://github.com/metal3-io/baremetal-operator/pull/497
> add job to check operator-sdk generation for baremetal-operator

- prow/config/config.yaml
Needs https://github.com/metal3-io/metal3-docs/pull/88
> add markdownlint job to metal3-docs repo

- prow/config/config.yaml
from metal3-io/ipam to metal3-io/metal3-ipam. Update Prow config accordingly
> Rename metal3-io/metal3-ipam repo

- prow/config/config.yaml
Depends-on: https://github.com/metal3-io/baremetal-operator/pull/527
> add golint job for baremetal-operator repository

- jenkins/README.md
- jenkins/jobs/integration_tests.pipeline
Update Jenkins document and remove unused variable.
> jenkins: Update doc and remove unused variable

- prow/config/config.yaml
- prow/manifests/deck-deployment.yaml
- prow/manifests/hook-deployment.yaml
- prow/manifests/horologium-deployment.yaml
- prow/manifests/plank-deployment.yaml
- prow/manifests/sinker-deployment.yaml
- prow/manifests/statusreconciler-deployment.yaml
- prow/manifests/tide-deployment.yaml
After merging and applying #103 to our CI cluster, two prow components failed to start. One needed a new argument and another needed a tweak to configuration.
> Address issues encountered with prow upgrade

- jenkins/scripts/files/run_integration_tests.sh
> Jenkins re-enable BMO image building for master jobs

- jenkins/scripts/files/run_integration_tests.sh
There was a mistake in the condition determining if it is a master run
> Jenkins: fix wrong condition for master runs

- jenkins/scripts/integration_clean.sh
The script was not removing the random string after the date
> Jenkins: fix name issue in cleanup script

- jenkins/OWNERS
also remove kanwar-saad due to inactivity
> Add kashifest and fmuyassarov as jenkins approvers

- prow/config/config.yaml
This adds the code generation test for IPAM added in https://github.com/metal3-io/ip-address-manager/pull/11 in the CI
> Add code generation job for IPAM

- jenkins/scripts/files/run_fetch_logs.sh
Fixes https://github.com/metal3-io/project-infra/issues/128
> Jenkins: fetch manifest at the of CI run

- jenkins/scripts/files/run_fetch_logs.sh
Fixes: https://github.com/metal3-io/metal3-dev-env/issues/438
> CI: Fix fetching qemu logs in Centos

- jenkins/scripts/files/run_fetch_logs.sh
https://github.com/metal3-io/project-infra/pull/139#discussion_r479900953
> CI: remove extra quotes

- jenkins/scripts/files/run_integration_tests.sh
https://github.com/metal3-io/project-infra/pull/145 is missing `then` in the conditional statement.
> Jenkins: Fix conditional statement

- prow/config/config.yaml
Depends on https://github.com/metal3-io/baremetal-operator/pull/648
> prow: run gomod.sh as a presubmit

- prow/config/config.yaml
> Add compulsory integration test for IPAM repo

- jenkins/scripts/files/run_integration_tests.sh
/cc @kashifest 
/cc @fmuyassarov
> Add support for IPAM testing

- jenkins/scripts/files/run_fetch_logs.sh
This PR adds fetching k8s logs post pivot.
> Fetch k8s logs post pivot

- jenkins/scripts/files/run_fetch_logs.sh
This PR will include the target cluster logs for all CI run.
> Add target cluster logs to all CI run.

- OWNERS
I'm more than happy to participate in the review process in project-infra repo, and I think it would be nice to extend the list here since the list is short, and not all the members might be available all the time.
> add fmuyassarov as reviewer

- prow/config/config.yaml
It's included in golint in PR https://github.com/metal3-io/baremetal-operator/pull/825
> Remove govet test

- OWNERS
Following community principle of adding reviewers, this PR adds Furkat (@furkatgofurov7 ) as a reviewer since he has 10 commits in this repository.
> Add Furkat as reviewer

- jenkins/README.md
Change test triggering phrases accordingly. 
Relative Gerrit JJB patch: [infra/cicd/9024](https://gerrit.nordix.org/c/infra/cicd/+/9024)
/hold until jjb patch is merged.
> 📖 Change test trigger commands

- jenkins/scripts/integration_test.sh
We are missing S character in the conditional.
> Jenkins: Fix missing S in the condition

- jenkins/scripts/files/run_fetch_logs.sh
Add atop and sysstat metrics to the Jenkins artifact tarball for analysis after runs.
> Fetch atop and sysstat metrics

- jenkins/scripts/files/run_integration_tests.sh
The location of k8s version export is not correct. It has to be done in the beginning.
> Fix the location of k8s version export

- prow/config/config.yaml
This removes white space in the configuration file.
> Prow: remove white space in the config yaml

- jenkins/scripts/fetch_logs.sh
- jenkins/scripts/integration_clean.sh
- jenkins/scripts/integration_delete.sh
- jenkins/scripts/integration_test_clean.sh
This PR will add the release check for FRA1 and add release in related files.
> Add release to master CI tests files

- jenkins/scripts/integration_clean.sh
This PR will modify the #271 to set it correctly.
> Fix integration cleanup file to add cleanup step for FRA1

- jenkins/scripts/fetch_logs.sh
- jenkins/scripts/integration_clean.sh
- jenkins/scripts/integration_delete.sh
- jenkins/scripts/integration_test.sh
- jenkins/scripts/integration_test_clean.sh
Run e2e PR tests in Frankfurt region
> Run e2e tests in FRA1

- OWNERS
According to community rules of getting a reviewer right after 10 commits, proposing smoshiur1237 to be a reviewer.
> Add smoshiur1237 as a reviewer

- jenkins/scripts/files/run_fetch_logs.sh
Now the script passes shellcheck.
> Fix syntax issues in log fetching script

- jenkins/scripts/bare_metal_lab/deploy-lab.yaml
- Power off BMHs before tearing down the source cluster
- Remove local container registry
- Prune containers, volumes and images
~~This depends on https://github.com/metal3-io/metal3-dev-env/pull/887~~
> Improve BML cleaning

- jenkins/README.md
See https://github.com/metal3-io/project-infra/pull/244 for more info.
> 📖 Remove prebaked volume notes from jenkins notes

- OWNERS
Russell is no longer focusing on this project.
> :seedling: Remove russellb as active approver

- jenkins/jobs/bml_integration_tests.pipeline
- jenkins/jobs/integration_tests.pipeline
- jenkins/jobs/integration_tests_clean.pipeline
- jenkins/scripts/bml_integration_test.sh
- jenkins/scripts/fetch_logs.sh
- jenkins/scripts/integration_test.sh
- jenkins/scripts/integration_test_clean.sh
- jenkins/scripts/utils.sh
switch to use new metal3ci CI user references.
> switch to use new ci user references

- jenkins/scripts/bare_metal_lab/deploy-lab.yaml
- jenkins/scripts/files/run_fetch_logs.sh
This PR dumps virtual serial port to a log file so the fetch log script can collect it.
> Get the serial log from Baremetal lab

- jenkins/scripts/integration_test.sh
- jenkins/scripts/utils.sh
It was unclear that the server was recreated after deletion. Adding a message to fix this.
> Clarify that the server is recreated when retrying

- prow/config/config.yaml
Related patch in IPAM: https://github.com/metal3-io/ip-address-manager/pull/106.
> Add gosec prow test for IPAM

- jenkins/scripts/integration_test_env.sh
Reverts metal3-io/project-infra#369
> Revert "Temporary fix while Nordix registry is down"

- jenkins/scripts/files/run_integration_tests.sh
- jenkins/scripts/integration_test_env.sh
Run e2e tests from all repos allowed in the JJB like project-infra https://gerrit.nordix.org/c/infra/cicd/+/13531
> Run e2e from all other repos

- jenkins/jobs/parallel_e2e_features_test.pipeline
- jenkins/scripts/files/run_integration_tests.sh
- jenkins/scripts/integration_test.sh
Create new pipeline to run e2e features test in parallel VMs and add the necessary changes in the scripts to avoid conflicts when preparing the vars.sh file for each VM
> Add side by side e2e feature tests

- jenkins/scripts/integration_delete.sh
This commit adds openstack commands to check and if possible
delete orphaned floating IPs from Fra1 region.
> Add deletion of orphaned Fra1 floating IPs

- jenkins/scripts/integration_test.sh
Increase ssh timeout on both client and server side
> Set TCPKeepAlive to no on ssh client and server side

- jenkins/scripts/bare_metal_lab/deploy-lab.yaml
I forgot to add the variable to the accepted variables in the last PR.
Also clean up /tmp/manifests
Fixes #406
> BML: Accept repo name over ssh

- jenkins/README.md
- jenkins/scripts/files/run_integration_tests.sh
- jenkins/scripts/integration_test_env.sh
- prow/config/config.yaml
Remove v1alpah4 CAPM3 related logic from the codebase since support has been dropped.
> 🌱 Remove CAPM3 v1alpha4 related logic from the code

- jenkins/scripts/files/run_fetch_logs.sh
> Fetch init container logs

- jenkins/README.md
- prow/config/config.yaml
and update document accordingly with new trigger phrases containing CAPM3 release branch names. 
Related to: https://gerrit.nordix.org/c/infra/cicd/+/14151
> Prow: Rename trigger phrases in CI

- OWNERS
Here are the contributions: https://github.com/metal3-io/project-infra/pulls?q=is%3Apr+author%3Amboukhalfa+is%3Aclosed+label%3Aapproved
> Add mohammed as reviewer

- jenkins/scripts/files/run_clean.sh
The cleanup script worked with the wron metal3 dev env path.
> Fix incorrect metal3 dev env path

- OWNERS
Adam has reached the required number of commits to become a reviewer in Project-infra
> Add Adam as a reviewer

- jenkins/scripts/bare_metal_lab/deploy-lab.yaml
Reflect changes in https://github.com/metal3-io/metal3-dev-env/pull/1110
> Change some env var names to same ones in CAPI

- jenkins/scripts/bare_metal_lab/deploy-lab.yaml
fixes the bml trigger on dev-env
> Fix the bml trigger on dev-env PRs

- OWNERS
Adding @Sunnatillo to reviewers list since he has reached the required [number of commits](https://github.com/metal3-io/project-infra/commits?author=Sunnatillo) to become a reviewer in this repo.
> 🌱 Add Sunnat as reviewer

- prow/config/config.yaml
Change rest of the registry.hub.docker.com references to docker.io
> prow: use images from docker.io

- prow/config/config.yaml
Pin gosec with version and digest.
> pin gosec with version and digest

- prow/config/config.yaml
- prow/config/plugins.yaml
As a first step this PR enables shellcheck prow test.
> Add prow test for Nordix/metal3-dev-tools

- jenkins/README.md
Documents `cherry-pick` and `transfer issue` plugins
> 📖  Document external prow plugins in the README

- jenkins/scripts/files/run_fetch_logs.sh
- jenkins/scripts/files/run_integration_tests.sh
Related PRs: 
https://github.com/metal3-io/metal3-dev-env/pull/1180
https://gerrit.nordix.org/c/infra/cicd/+/17602
> ⚠️ Remove ansible upgrade test as it was replaced by e2e upgrade

- jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
Referred dev env PR:
https://github.com/metal3-io/metal3-dev-env/pull/1169
> Change bridge name to external, after renaming it in metal3-dev-env

- jenkins/scripts/files/run_fetch_logs.sh
This will add improvement in the target log collection script
> Refactor target log collection script

- jenkins/scripts/fetch_logs.sh
- jenkins/scripts/integration_delete.sh
- jenkins/scripts/integration_test.sh
- jenkins/scripts/integration_test_clean.sh
Lately cleura Fra1 is not stable we are moving e2e tests to kna1
> Run e2e on default region

- jenkins/scripts/fetch_logs.sh
- jenkins/scripts/integration_delete.sh
- jenkins/scripts/integration_test.sh
- jenkins/scripts/integration_test_clean.sh
Reverts metal3-io/project-infra#517
> Revert "Run e2e on default region"

- hack/shellcheck.sh
- jenkins/scripts/bml_cleanup.sh
- jenkins/scripts/bml_integration_test.sh
- jenkins/scripts/fetch_logs.sh
- jenkins/scripts/files/run_clean.sh
- jenkins/scripts/files/run_fetch_logs.sh
- jenkins/scripts/files/run_integration_tests.sh
- jenkins/scripts/integration_clean.sh
- jenkins/scripts/integration_delete.sh
- jenkins/scripts/integration_test.sh
- jenkins/scripts/integration_test_clean.sh
- jenkins/scripts/integration_test_env.sh
- jenkins/scripts/ironic_build_test.sh
- jenkins/scripts/ironic_image_build_test_delete.sh
- jenkins/scripts/start_ironic_image_build_test.sh
- jenkins/scripts/utils.sh
- prow/manifests/overlays/metal3/config.yaml
Add `hack/shellcheck.sh` and prow config in one commit.
Fix all the shellcheck complaints and formatting in another.
> add shellcheck

- jenkins/README.md
- prow/manifests/overlays/metal3/config.yaml
This PR drops the CI support for CAPM3/IPAM release-1.1 branch.
> Drop CAPM3 release-1.1 CI support

- prow/capo-cluster/kubeadmcontrolplane.yaml
- prow/capo-cluster/machinedeployment.yaml
- prow/capo-cluster/openstackmachinetemplates.yaml
- prow/cluster-resources/kustomization.yaml
Should not be merged before #520.
> Prow: Upgrade k8s to v1.26.5

- prow/manifests/overlays/metal3/plugins.yaml
In case we want to override test results from non-required tests, we could use override plugin.
> add override plugin to prow

- jenkins/jobs/integration_tests.pipeline
Added integration timeout update to two hours
> :sparkles: Added integration timeout update to two hours

- jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
> Fix hanging at vsp log collection  ansible task in bml jobs

- jenkins/jobs/bml_integration_tests.pipeline
This PR add 3 hours timeout for bml interation tests
> Add timeout for bml integration tests

- prow/manifests/overlays/metal3/config.yaml
> Bump golang to v1.20 for ipam main branch prow tests

- jenkins/scripts/integration_test.sh
Now matches that of normal e2e integration tests.
> Changed e2e basic test flavor

- jenkins/scripts/files/run_fetch_logs.sh
We are missing some logs during the failure in target log collection. Where pods are not running and need describe logs to debug. Because if pods are not running, no logs will be generated by it. So adding describe pods output will tell us the reason of the failure of the pods.
> Add describe pods output during log collection

- prow/manifests/overlays/metal3/config.yaml
> Bump golang version to v1.20 for bmo main branch prow tests

- prow/cluster-resources/kustomization.yaml
- prow/infra/kustomization.yaml
Calico v3.26.1
Ingress-nginx v1.8.1
> Prow: Bump ingress-nginx and calico versions

- jenkins/jobs/integration_tests.pipeline
- jenkins/scripts/files/run_integration_tests.sh
- jenkins/scripts/integration_test.sh
Remove mentions of ansible based feature tests since ansible based feature tests are deprecated and removed.
> Remove mentions of ansible based feature tests 

- jenkins/scripts/files/run_integration_tests.sh
> Fix KUBECTL_SHA256 unbound variable for bml tests

- prow/manifests/overlays/metal3/config.yaml
> fix make invocation for IPAM make test

- jenkins/jobs/bmo_e2e_tests.pipeline
See also https://github.com/metal3-io/baremetal-operator/pull/1303
> Add BMO e2e pipeline

- prow/cluster-resources/kustomization.yaml
Bump cloud-provider-openstack to 1.28.0
> Bump cloud-provider-openstack to 1.28.0

- jenkins/scripts/integration_test.sh
Tests after https://github.com/metal3-io/project-infra/pull/563 can run in different projects this change show the project in the logs
> Echo in which project the test is running

- prow/manifests/overlays/metal3/config.yaml
> add markdownlint for dev-tools repo

- prow/manifests/overlays/metal3/config.yaml
> Bump golang to v1.21 for IPAM prow jobs

- jenkins/image_building/README.md
- jenkins/image_building/build-ci-image.sh
- jenkins/image_building/dib_elements/centos-ci/README.md
- jenkins/image_building/dib_elements/centos-ci/element-deps
- jenkins/image_building/dib_elements/centos-ci/install.d/install
- jenkins/image_building/dib_elements/centos-ci/post-install.d/configure
- jenkins/image_building/dib_elements/ci-base/README.md
- jenkins/image_building/dib_elements/ci-base/element-deps
- jenkins/image_building/dib_elements/ci-base/package-installs.yaml
- jenkins/image_building/dib_elements/ci-base/pkg-map
- jenkins/image_building/dib_elements/ubuntu-ci/README.md
- jenkins/image_building/dib_elements/ubuntu-ci/element-deps
- jenkins/image_building/dib_elements/ubuntu-ci/install.d/install
- jenkins/image_building/dib_elements/ubuntu-ci/post-install.d/configure
- jenkins/image_building/id_ed25519_metal3ci.pub
- jenkins/jobs/openstack_ci_image_building.pipeline
This PR adds image building workflow with DiskImage Builder.
> Add image building with diskimage-builder

- jenkins/jobs/prow_integration_tests.pipeline
Fix some issue do not use `def` for some vars and remove unused declarations
> Update prow integration tests pipeline

- jenkins/jobs/bmo_e2e_tests.pipeline
We should merge the PR branch to the base branch before we start the build.
> BMO e2e merge before build

- prow/manifests/overlays/metal3/config.yaml
Fix BMO required tests to match reality.
> fix BMO required tests to match GH settings

- jenkins/scripts/integration_test.sh
- jenkins/scripts/utils.sh
Reverts metal3-io/project-infra#645
> Revert "Check CI VM cloud-init exit code instead of output"

- jenkins/jobs/prow_integration_tests.pipeline
The project infra link was wrong
> fix project-infra url

- .gitignore
- jenkins/jobs/capm3-e2e-tests.pipeline
Adding clusterctl upgrade test pipeline
> 🌱 clusterctl upgrade test

- prow/manifests/overlays/metal3/config.yaml
linked to the changes https://gerrit.nordix.org/c/infra/cicd/+/20751
> Add e2e integration trigger to prow

- jenkins/jobs/capm3-e2e-tests.pipeline
removing VM_KEY e2e pipeline, not needed anymore
> 🌱 removing VM_KEY, not needed anymore

- prow/manifests/overlays/metal3/config.yaml
Part of migrating tests to be triggerable from prow using prow jenkins operator.This PR updates prow config with triggers
> Add feature tests triggers to prow config

- jenkins/jobs/parallel_e2e_features_test.pipeline
This PR updating the feature tests pipeline to handle the triggering them from prow
> Update feature tests pipeline to trigger them from prow

- jenkins/jobs/capm3-e2e-tests.pipeline
- prow/manifests/overlays/metal3/config.yaml
linked to the jjb changes https://gerrit.nordix.org/c/infra/cicd/+/20818
> Trigger upgrade tests from prow

- jenkins/jobs/capm3-e2e-tests.pipeline
- prow/manifests/overlays/metal3/config.yaml
Specify branches on capm3 and bmo where tests should run and fix typo in the pipeline
> Fix upgrade test pipeline and set the trigger branches

- jenkins/jobs/capm3-e2e-tests.pipeline
- jenkins/jobs/parallel_e2e_features_test.pipeline
- jenkins/jobs/prow_integration_tests.pipeline
fix https://jenkins.nordix.org/view/Metal3%20Periodic/
> Fix missing refspec var

- jenkins/jobs/capm3-e2e-tests.pipeline
- prow/manifests/overlays/metal3/config.yaml
Fix failing when trying to merge the PR commits into the tested repo and update keep job name
> Add PR_ID to upgrade pipeline

- prow/manifests/overlays/metal3/config.yaml
This PR adds e2e integration test triggers to prow config under ironic-image repo
> Run e2e on ironic-image repo

- prow/manifests/overlays/metal3/config.yaml
on several repos.
TODO: other repos still not running e2e tests 
ironic-ipa-downloader
ironic-standalone-operator
mariadb-image
> Make tests triggered with prow required instead of ghprb

- prow/manifests/overlays/metal3/config.yaml
> Make two tests required on main and only ubuntu on releases

- jenkins/jobs/integration_tests_clean.pipeline
Migrating itegration clean to prow jenkins operator 
Depends on https://gerrit.nordix.org/c/infra/cicd/+/20824
> Trigger integration clean from prow

- prow/manifests/overlays/metal3/config.yaml
Add prow triggered test on the following repos
ironic-ipa-downloader
mariadb-image
> Make e2e run on other repos from prow

- jenkins/scripts/integration_test.sh
> Fail on pipe failure for openstack commands

- prow/manifests/overlays/metal3/config.yaml
New branches were put under the wrong prow config. This PR is fixing that.
> 🐛 Fixes related to release capm3/ipam 1.7 and bmo 0.6.0

- prow/manifests/overlays/metal3/config.yaml
- prow/manifests/overlays/metal3/external-plugins/needs-rebase_deployment.yaml
- prow/manifests/overlays/metal3/labels.yaml
- prow/manifests/overlays/metal3/plugins.yaml
This has been mixed bag and its getting annoying. We have few big files not matching with the rest, so I'll pull the trigger for this now.
> make all prow config k8s yaml indented

- jenkins/jobs/dev_env_integration_tests.pipeline
- jenkins/jobs/integration_tests_clean.pipeline
- jenkins/jobs/parallel_e2e_features_test.pipeline
Removing indentation or extra spaces from pipeline files
> Remove indentation space from pipeline files

- jenkins/image_building/dib_elements/centos-ci/install.d/55-install
- jenkins/image_building/dib_elements/ci-base/package-installs.yaml
- jenkins/image_building/dib_elements/ci-base/pkg-map
- jenkins/image_building/dib_elements/ubuntu-ci/install.d/55-install
Add left out packages related to libvirt when we move to DiskImage builder
> Add libvirt related packages for CI image

- jenkins/jobs/dev_env_integration_tests.pipeline
- jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
> Fix unbound UPDATED_REPO error on dev env tests

- jenkins/jobs/capm3-e2e-tests.pipeline
ci_git_url was metal3 instead of metal3-io, this PR is fixing it.
> Minor fix related to ci_git_url

- jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
Tests are failing with
` ./jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh: line 27: EPHEMERAL_TEST: unbound variable` error after dynamic worker changes.
This PR fixes this issue
> Fix unsetting unbound vars

- prow/manifests/overlays/metal3/config.yaml
Add prefix to the triggers and add the missing triggers to the some repos and remove them where not needed
> 🌱 Fix dev-env triggers

- prow/manifests/overlays/metal3/config.yaml
Release-0.3 is no longer supported even in CI. Remove it. Also add some empty lines between components to separate the components for readability.
> remove bmo release-0.3 from project-infra

- jenkins/image_building/build-image.sh
CRIO v1.30.0 supports k8s v1.30.x.
> Bump CRIO to v1.30.0

- OWNERS
**What this PR does / why we need it**:
I can't commit to being an approver in this repo, so I am moving myself to emeritus approvers.
> 🌱 Move furkatgofurov7 to emeritus approvers

- jenkins/jobs/parallel_e2e_features_test.pipeline
We fully moved to jenkins prow operator in feature tests. This PR removes ghprb related variables from feature tests pipeline
> Remove ghprb related variables from feature tests pipeline

- prow/README.md
Fix typos, update and add some new things that were missing. Most notably, the Prow CRDs are now fetched from the new prow repository.
> Prow: Update readme

- jenkins/jobs/bml_integration_tests.pipeline
Removes ghprb related vars from bare metal lab pipeline
> Remove ghprb vars from bml pipeline

- prow/README.md
- prow/capo-cluster/openstackcluster.yaml
- prow/infra/service.yaml
This updates a few things in the readme. Also the bastion image and loadbalancer IP is changed.
> Changes related to rebuilding the Prow cluster

- prow/README.md
- prow/capo-cluster/infra-md.yaml
- prow/capo-cluster/kubeadmcontrolplane.yaml
- prow/capo-cluster/machinedeployment.yaml
- prow/capo-cluster/openstackcluster.yaml
- prow/capo-cluster/openstackmachinetemplates.yaml
- prow/infra/service.yaml
- prow/manifests/base/hook.yaml
All manifests and docs updated to reflect the move.
> Move Prow to Xerces

- prow/manifests/overlays/metal3/config.yaml
Signed-off-by: Riccardo Pittau <elfosardo@gmail.com>
> Update config for ironic-image release-25.0

- jenkins/scripts/dynamic_worker_workflow/fetch_logs.sh
- jenkins/scripts/files/run_fetch_logs.sh
This will add the capability to add manifest in failed test and will improve the debugging capability.
> Fix manifest collection in failed test

- jenkins/jobs/bml_integration_tests.pipeline
- jenkins/scripts/bare_metal_lab/default_vars/vars.yaml
- jenkins/scripts/bare_metal_lab/tasks/cleanup-tasks.yaml
- jenkins/scripts/bml_cleanup.sh
- jenkins/scripts/bml_integration_test.sh
This PR  fixes issue of merging test PR branch when we run bml tests on a pull request (for example in metal3-dev-env). 
Implements https://github.com/metal3-io/project-infra/pull/677 for bml
> Fix merging PR branch in bml tests

- jenkins/image_building/build-image.sh
- jenkins/image_building/upload-ci-image.sh
- jenkins/jobs/image_building.pipeline
This PR updates image upload to both xerces and Cleura. 
> Push CI images to both Xerces and Cleura

- jenkins/image_building/build-image.sh
Set disk image builder to latest 3.33.0 version. Also some more minor fixes
> Set disk image builder to latest 3.33.0 version

- jenkins/image_building/build-image.sh
In node image building script, if a failure happens in the middle of the script, the node image and the `dib` directory should be cleaned, so that the next pipeline can start.
For e.g. in https://jenkins.nordix.org/job/metal3_periodic_node_image_building/32/execution/node/62/log/
```
+ mkdir /home/****/workspace/metal3_periodic_node_image_building/jenkins/image_building/dib
mkdir: cannot create directory ‘/home/****/workspace/metal3_periodic_node_image_building/jenkins/image_building/dib’: File exists
```
> :seedling: Set trap to cleanup in build-image.sh

- prow/manifests/overlays/metal3/config.yaml
This will add and update the triggers which will be ran by PROW in PRs
> Update PROW config feature tests triggers

- prow/manifests/overlays/metal3/config.yaml
This is needed for this PR in IPAM: https://github.com/metal3-io/ip-address-manager/pull/607
> Test ipam 1.7 release with go 1.22

- .github/workflows/container-image-build.yml
Permissions:contents:read should be enough for this usecase.
> :seedling: Changing default permissions in container-image-build-wf to read

- prow/manifests/overlays/metal3/config.yaml
reference https://github.com/metal3-io/metal3-docs/pull/465
> Remove EoL ironic-image 23.1 from config

- jenkins/jobs/capm3-e2e-tests.pipeline
- jenkins/jobs/dev_env_integration_tests.pipeline
This PR matches agent label with actual flavor in private openstack cloud for jenkins worker.
> Fix agent label with actual flavor

- jenkins/README.md
- prow/manifests/overlays/metal3/config.yaml
Updates the prow config and README for CAPM3 and IPAM release-1.8 configurations.
> :seedling: Add release-1.8 configurations

- jenkins/image_building/upload-ci-image.sh
This pr removes uploading to fra region as we are moving to kna.
> Do not upload images to fra region

- prow/manifests/overlays/metal3/config.yaml
Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>
> Update config for ironic-image release-26.0

- prow/manifests/overlays/metal3/config.yaml
Too many and/or wrong tests were added to IPAM and ironic-image, so cleanup extras.
> fix required tests in prow config for ipam and ironic-image

- prow/manifests/overlays/metal3/config.yaml
Remove BMO release-0.4 from Prow, and add missing release-0.8 tests.
> remove BMO 0.4 from Prow and add missing 0.8 tests

- jenkins/README.md
- prow/manifests/overlays/metal3/config.yaml
Remove tests related to release-1.5
> :seedling: Remove tests related to release-1.5

- .github/workflows/container-image-build.yml
> fix image-tag reference

- jenkins/image_building/initrd_sdk/README.md
- jenkins/image_building/initrd_sdk/unlock-mount-luks.sh
This commit:
- Introduces the concept of the initrd SDK in support of disk image building
- Adds a short README explaining the goal of the initrd SDK
- Adds the first script to the SDK
> add initial commit of the initrd sdk

- .cspell-config.json
- hack/spellcheck.sh
- jenkins/README.md
- jenkins/image_building/dib_elements/ubuntu-node/README.md
- jenkins/image_building/initrd_sdk/README.md
- prow/README.md
- prow/manifests/overlays/metal3/config.yaml
Add spellcheck.sh from metal3-docs and fix found issues.
> add spellcheck basic test and fix spellcheck issues

- jenkins/image_building/build-image.sh
Uplifts kubernetes version to v1.31.2 for image building. Also uplifts crio
> 🌱 uplift k8s to v1.31.2

- hack/prow_test_dumper.py
This is needed to handle the now split up presubmit jobs.
> Update prow_test_dumper.py to handle job-config

- .github/workflows/build-images-action.yml
- prow/container-images/basic-checks/Dockerfile
Update basic-checks image to Go 1.23.3.
> update basic-checks image to Go 1.23

- jenkins/jobs/capm3-e2e-tests.pipeline
- jenkins/jobs/dynamic_fullstack_building.pipeline
- jenkins/jobs/e2e_features_test.pipeline
Moves ephemeral, fullstack, pivoting and remediation tests to private cloud
> Move rest of the test to private cloud

- prow/config/jobs/metal3-io/ip-address-manager-release-1.9.yaml
> add IPAM 1.9 release to Prow

- prow/config/jobs/metal3-io/baremetal-operator-release-0.9.yaml
Add BMO release-0.9 branch to Prow.
> add BMO release-0.9 to Prow

- OWNERS_ALIASES
Huy has plenty of commits in project-infra and has done good work with the container building pipelines.
> add mquhuy as reviewer

- jenkins/jobs/image_building.pipeline
Adds vars to image building pipeline for building node images with older versions of k8s
> Add vars to image building pipeline

- jenkins/image_building/upload-ci-image.sh
- jenkins/jobs/clean_resources.pipeline
- jenkins/jobs/image_building.pipeline
- jenkins/scripts/clean_resources.sh
As we stopped using cleura we are removing image upload functions to cleura.
> Remove uploading ci images to cleura

- jenkins/image_building/build-image.sh
Bumping k8s and CRIO to latest patch version for v1.32.x
> Bump k8s to v1.32.1 and CRIO to v1.32.1

- OWNERS
- OWNERS_ALIASES
@mquhuy is not active as a reviewer in this project anymore. Thanks Huy for all your contributions.
> Move @mquhuy to emeritus reviewers

- jenkins/image_building/build-image.sh
Uplift Kubernetes version to v1.33.0 for image building
> :seedling:  Uplift Kubernetes version to v1.33.0 for image building

- prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.10.yaml
Add CAPM3 release-1.10 to Prow
> :seedling: Add CAPM3 release-1.10 to Prow

- prow/config/jobs/metal3-io/ip-address-manager-release-1.10.yaml
> :seedling: Add IPAM release-1.10 to Prow

- prow/config/jobs/metal3-io/baremetal-operator-release-0.10.yaml
> :seedling: Add BMO release-0.10 to Prow

- jenkins/README.md
- prow/config/jobs/metal3-io/ironic-image-release-28.0.yaml
- prow/config/jobs/metal3-io/ironic-ipa-downloader.yaml
- prow/config/jobs/metal3-io/mariadb-image.yaml
- prow/config/jobs/metal3-io/metal3-dev-env.yaml
- prow/config/plugins.yaml
Add other release-1.10 triggers to Prow
> :seedling: Add other release-1.10 triggers to Prow

- prow/config/jobs/metal3-io/metal3-dev-env.yaml
- prow/config/jobs/metal3-io/project-infra.yaml
Changing mandatory tests for metal3-dev-env and 1.9,1.10 for project-infra
> 🌱 Changing mandatory tests for metal3-dev-env and adding 1.9,1.10 for project-infra

- .github/workflows/pr-link-check.yml
Get upstream as an input from the workflow calling this workflow ore use project infra as default.
> :seedling: Set upstream to PR link check

- .github/workflows/pr-link-check.yml
> :seedling: Fix input in PR-link-check

- jenkins/scripts/bare_metal_lab/tasks/cleanup-tasks.yaml
- jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
First attempt caused an ansible task failure. fixing it in this PR.
> Fix ansible task error caused by lingering dnsmasq ansible task

- prow/capi/bootstrap.yaml
- prow/capi/control-plane.yaml
- prow/capi/core.yaml
- prow/capi/infrastructure.yaml
- prow/capi/kustomization.yaml
- CAPI core v1.10.1
- KubeadmBootstrap v1.10.1
- KubeadmControlPlane v1.10.1
- CAPO v0.12.3
- ORC v2.1.0
- CAPI operator v0.19.0
Changes have been applied in the cluster.
> Prow: Bump CAPI components

- jenkins/image_building/dib_elements/centos-node/install.d/55-install
- jenkins/image_building/dib_elements/centos-node/package-installs.yaml
- jenkins/image_building/dib_elements/ubuntu-node/package-installs.yaml
This PR installs python related packages to run ansible script on node images.
> Install python related packages to run ansible script on node images

- jenkins/image_building/build-image.sh
- jenkins/image_building/dib_elements/ubuntu-node/install.d/55-install
This PR add support for Ubuntu 24.04 node images
> Add support for Ubuntu 24.04 node images

- prow/config/jobs/metal3-io/ironic-image-release-31.0.yaml
- prow/config/plugins.yaml
Add CI support for ironic-image release-31.0 branch.
> Add configuration for ironic-image release-31.0

- jenkins/image_building/dib_elements/centos-node/install.d/55-install
- jenkins/image_building/dib_elements/centos-node/pre-install.d/55-setup-repos
- jenkins/image_building/dib_elements/ubuntu-node/install.d/55-install
- jenkins/image_building/dib_elements/ubuntu-node/pre-install.d/55-setup-repos
Remove alternative path that was used for installations depending on the release type.
> Unify Kubernetes installation scripts in image building

- jenkins/image_building/build-image.sh
Bump k8s to 1.34 for image building
> 🌱 Bump k8s to 1.34 for image building

- jenkins/scripts/clean_resources.sh
Fixes Resource cleanup script which is failing with error "externally-managed-environment".
P.S [Adam]
https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3
> Fix clean resources script

- jenkins/scripts/clean_resources.sh
This PR is followup to
https://github.com/metal3-io/project-infra/pull/1084
> Install python3.12-venv for resource cleanup script

- jenkins/jobs/capm3-e2e-tests.pipeline
Change scalability test timeout to 3 hours
> 🌱 Change scalability test timeout to 3 hours

- jenkins/jobs/image_building.pipeline
> Fix OpenSUSE image OS
